"use strict";
/* ═══════════════════════════════════════════════════════════════════════
   FinMath Curriculum Arena — shared page logic. One shell, five page types,
   any curriculum: nothing in this file names an institution, a programme, a
   course or a skill.

   DATA FILES (all plain <script> globals, so the site works from file:// too)
     site_params.js   → window.SITE_PARAMS   the ONLY file naming the school
     program.js       → window.PROGRAM       blocks, concentrations, quarters,
                                             components, the course index
     skills.js        → window.SKILLS        GENERATED by tools/build_skills.py
                                             from courses/*.js: the shared tag
                                             vocabulary plus a COMPACT course
                                             index (weeks / concepts / mcq
                                             counts, prerequisites, tags)
     courses/<slug>.js→ window.COURSES[CODE]  the deep course object; loaded
                                             LAZILY by course.html only, by
                                             injecting one <script> tag
     widgets.js       → window.WIDGETS       the widget renderer (course page)

   Every one of them is optional. A missing program.js degrades the map to
   whatever skills.js knows; a missing skills.js degrades the filters; a
   missing widgets.js leaves a readable note where a widget would be. The
   page never throws and never logs to the console — tools/sweep.py asserts
   zero console errors on every page, at two viewport widths, after clicking
   every control.

   PAGES (body[data-page])
     index          the program map: filters by block / concentration /
                    quarter / skill, hover-prerequisites, per-course progress
     course         course.html?c=FINM-33000 (or window.COURSE_CODE from a
                    static wrapper) — the deep page
     concentration  concentration.html?c=financial-computing
     quarter        quarter.html
     skills         skills.html#<tag>

   PROGRESS (localStorage, namespace SITE_PARAMS.storage_prefix)
     <prefix>:w:<slug>:<n>        "1"   week n of this course was opened
     <prefix>:q:<slug>:<n>:<i>    "1"|"0"  MCQ i of week n answered right/wrong
   Counting is done by scanning keys, so no index of week numbers is needed
   and a course that gains a week does not invalidate anything.

   ALL data text reaches the DOM through textContent. `explain` is the ONE
   field SCHEMA.md allows plain HTML in; it goes through a strict allow-list
   sanitiser (sanitizeHtml below), never straight into innerHTML.
   ═══════════════════════════════════════════════════════════════════════ */
(function () {

  /* ══════════════ tiny DOM helpers ══════════════ */
  function $(id) { return document.getElementById(id); }
  function el(tag, cls, text) {
    var e = document.createElement(tag);
    if (cls) e.className = cls;
    if (text !== undefined && text !== null) e.textContent = String(text);
    return e;
  }
  function add(parent, child) { if (parent && child) parent.appendChild(child); return child; }
  function clear(n) { while (n && n.firstChild) n.removeChild(n.firstChild); }
  function show(node, on) { if (node) node.hidden = !on; }
  function txt(v) { return v === undefined || v === null ? "" : String(v); }
  function trim(v) { return txt(v).replace(/^\s+/, "").replace(/\s+$/, ""); }
  function arr(v) { return Object.prototype.toString.call(v) === "[object Array]" ? v : []; }
  function obj(v) { return v && typeof v === "object" ? v : {}; }
  function num(v, d) { var n = Number(v); return isFinite(n) ? n : d; }
  function domId(s) { return txt(s).replace(/[^A-Za-z0-9_-]+/g, "-").replace(/^-+|-+$/g, "") || "x"; }
  function has(o, k) { return Object.prototype.hasOwnProperty.call(o, k); }
  function indexOf(list, v) { for (var i = 0; i < list.length; i++) if (list[i] === v) return i; return -1; }
  function pct(a, b) { return b > 0 ? Math.round((a / b) * 100) : 0; }
  function plural(n, one, many) { return n === 1 ? one : (many || one + "s"); }

  /* Query string, ES5, tolerant of "+" and percent-encoding. */
  function qs(name) {
    var s = window.location.search || "", i, kv, parts;
    if (s.charAt(0) === "?") s = s.slice(1);
    parts = s.split("&");
    for (i = 0; i < parts.length; i++) {
      kv = parts[i].split("=");
      if (decodeURIComponent(kv[0].replace(/\+/g, " ")) === name) {
        return decodeURIComponent((kv[1] || "").replace(/\+/g, " "));
      }
    }
    return "";
  }

  /* ══════════════ site params ══════════════ */
  var SP_DEFAULTS = {
    institution: "the university", institution_short: "the university",
    program: "the programme", program_short: "the programme",
    degree: "the degree", site_title: "Curriculum Arena",
    program_url: "", catalog_url: "", site_url: "", source_url: "",
    contact: "", storage_prefix: "finmath-arena",
    accent: "#800000", accent_2: "#800000"
  };
  var SP = {};
  (function () {
    var src = obj(window.SITE_PARAMS), k;
    for (k in SP_DEFAULTS) if (has(SP_DEFAULTS, k)) SP[k] = SP_DEFAULTS[k];
    for (k in src) if (has(src, k) && src[k] !== "" && src[k] !== null && src[k] !== undefined) SP[k] = src[k];
  }());
  function sp(k, dflt) { var v = trim(SP[k]); return v ? v : (dflt === undefined ? "" : dflt); }

  /* ══════════════ accents → CSS custom properties ══════════════ */
  function parseHex(v) {
    var h = trim(v).replace(/^#/, "");
    if (/^[0-9a-fA-F]{3}$/.test(h)) h = h.charAt(0) + h.charAt(0) + h.charAt(1) + h.charAt(1) + h.charAt(2) + h.charAt(2);
    if (!/^[0-9a-fA-F]{6}$/.test(h)) return null;
    return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
  }
  function toHex(c) {
    var out = "#", k, s;
    for (k = 0; k < 3; k++) {
      s = Math.max(0, Math.min(255, Math.round(c[k]))).toString(16);
      out += s.length < 2 ? "0" + s : s;
    }
    return out;
  }
  function tint(c, t) { return [c[0] + (255 - c[0]) * t, c[1] + (255 - c[1]) * t, c[2] + (255 - c[2]) * t]; }
  function shade(c, t) { return [c[0] * (1 - t), c[1] * (1 - t), c[2] * (1 - t)]; }
  function rgbList(c) { return Math.round(c[0]) + "," + Math.round(c[1]) + "," + Math.round(c[2]); }
  function applyAccent(hex) {
    var root = document.documentElement, a1 = parseHex(hex), a2, a3, ad;
    if (!root || !root.style || !root.style.setProperty || !a1) return;
    a2 = a1; a3 = shade(a1, 0.28); ad = shade(a1, 0.4);   /* light page: links = accent, code ink darker */
    function set(n, v) { try { root.style.setProperty(n, v); } catch (e) { /* ignore */ } }
    set("--accent", toHex(a1)); set("--accent-2", toHex(a2));
    set("--accent-3", toHex(a3)); set("--accent-deep", toHex(ad));
    set("--accent-rgb", rgbList(a1)); set("--accent-2-rgb", rgbList(a2));
  }
  applyAccent(sp("accent"));

  /* ══════════════ progress store ══════════════ */
  var PREFIX = sp("storage_prefix", "finmath-arena") + ":";
  var mem = {}, useLS = true;
  try {
    window.localStorage.setItem(PREFIX + "__probe", "1");
    window.localStorage.removeItem(PREFIX + "__probe");
  } catch (e) { useLS = false; }
  var store = {
    get: function (k) {
      if (!useLS) return has(mem, k) ? mem[k] : null;
      try { return window.localStorage.getItem(PREFIX + k); } catch (e) { return has(mem, k) ? mem[k] : null; }
    },
    set: function (k, v) {
      mem[k] = v;
      if (!useLS) return;
      try {
        if (v === null) window.localStorage.removeItem(PREFIX + k);
        else window.localStorage.setItem(PREFIX + k, String(v));
      } catch (e) { useLS = false; }
    },
    /* every key under the namespace whose remainder starts with `pre` */
    scan: function (pre) {
      var out = {}, i, k, full = PREFIX + pre;
      if (!useLS) {
        for (k in mem) if (has(mem, k) && k.indexOf(pre) === 0) out[k.slice(pre.length)] = mem[k];
        return out;
      }
      try {
        for (i = 0; i < window.localStorage.length; i++) {
          k = window.localStorage.key(i);
          if (k && k.indexOf(full) === 0) out[k.slice(full.length)] = window.localStorage.getItem(k);
        }
      } catch (e) { /* ignore */ }
      return out;
    },
    reset: function () {
      mem = {};
      if (!useLS) return;
      try {
        var kill = [], i, k;
        for (i = 0; i < window.localStorage.length; i++) {
          k = window.localStorage.key(i);
          if (k && k.indexOf(PREFIX) === 0) kill.push(k);
        }
        for (i = 0; i < kill.length; i++) window.localStorage.removeItem(kill[i]);
      } catch (e) { /* ignore */ }
    },
    available: function () { return useLS; }
  };

  /* per-course progress, counted by scanning keys (no week index needed).
     An MCQ value is "<0|1>:<chosen index>": the leading flag says whether the
     answer was right, the index says what was clicked, so a reload replays the
     exact feedback the student saw rather than guessing a wrong option. */
  function rightFlag(v) { return txt(v).charAt(0) === "1"; }
  function chosenOf(v) { var p = txt(v).split(":"); return p.length > 1 ? num(p[1], -1) : -1; }
  function progressOf(slug) {
    var w = store.scan("w:" + slug + ":"), q = store.scan("q:" + slug + ":"), k;
    var weeks = 0, answered = 0, right = 0;
    for (k in w) if (has(w, k) && w[k] === "1") weeks++;
    for (k in q) if (has(q, k)) { answered++; if (rightFlag(q[k])) right++; }
    return { weeks: weeks, answered: answered, right: right };
  }

  /* ══════════════ code / slug normalisation ══════════════ */
  /* canonical key: letters+digits, uppercase. "FINM 33000" / "finm-33000" →
     "FINM33000". Used for every lookup so the three spellings interoperate. */
  function ckey(s) { return txt(s).toUpperCase().replace(/[^A-Z0-9]+/g, ""); }
  function slugOf(code) {
    var s = txt(code).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
    if (s.indexOf("-") < 0) s = s.replace(/([a-z])(\d)/, "$1-$2");
    return s;
  }
  function codeOf(slug) {
    var parts = txt(slug).split("-"), i, out = [];
    for (i = 0; i < parts.length; i++) if (parts[i]) out.push(parts[i].toUpperCase());
    return out.join(" ");
  }
  /* find every course code mentioned inside a free-text string */
  var CODE_RE = /\b([A-Z]{3,5})[\s\-]?(\d{4,5})\b/g;
  function codesIn(text) {
    var s = txt(text), out = [], m;
    CODE_RE.lastIndex = 0;
    while ((m = CODE_RE.exec(s)) !== null) out.push(m[1] + " " + m[2]);
    return out;
  }

  /* ══════════════ the data model ══════════════ */
  var P = obj(window.PROGRAM);
  var SK = obj(window.SKILLS);
  var BLOCKS = arr(P.blocks);
  var CONCS = arr(P.concentrations);
  var QUARTERS = arr(P.quarters).length ? arr(P.quarters) : ["Autumn", "Winter", "Spring", "Summer"];
  var COMPONENTS = arr(P.components);
  var TAGS = arr(SK.tags);
  var CATS = arr(SK.categories);

  var concById = {}, blockById = {}, catById = {}, tagByName = {};
  (function () {
    var i;
    for (i = 0; i < CONCS.length; i++) if (CONCS[i] && CONCS[i].id) concById[CONCS[i].id] = CONCS[i];
    for (i = 0; i < BLOCKS.length; i++) if (BLOCKS[i] && BLOCKS[i].id) blockById[BLOCKS[i].id] = BLOCKS[i];
    for (i = 0; i < CATS.length; i++) if (CATS[i] && CATS[i].id) catById[CATS[i].id] = CATS[i];
    for (i = 0; i < TAGS.length; i++) if (TAGS[i] && TAGS[i].tag) tagByName[TAGS[i].tag] = TAGS[i];
  }());
  function concOf(id) { return concById[id] || { id: id, name: id, accent: "" }; }
  function blockOf(id) { return blockById[id] || { id: id, name: id || "unplaced", units: 0 }; }
  function catOf(id) { return catById[id] || { id: id || "other", name: id || "other", color: "#767676" }; }
  function tagLabel(t) { var r = tagByName[t]; return (r && trim(r.name)) || txt(t).replace(/-/g, " "); }
  function accentOfCourse(c) {
    var ids = arr(c && c.concentrations), i, a;
    for (i = 0; i < ids.length; i++) { a = trim(concOf(ids[i]).accent); if (a) return a; }
    return "";
  }

  /* ── build the merged course index ──────────────────────────────────
     Three possible sources, merged in this order (later wins on a field it
     actually supplies): blocks/concentrations membership → PROGRAM.courses →
     SKILLS.courses → a deep window.COURSES object if one happens to be
     loaded. Nothing is required; a code seen only in a block list still
     produces a usable card. */
  var IDX = {}, ORDER = [];
  function touch(code) {
    var k = ckey(code);
    if (!k) return null;
    if (!IDX[k]) {
      IDX[k] = { key: k, code: txt(code), slug: slugOf(code), title: "", instructor: "",
                 quarter: "", units: 0, block: "", concentrations: [], tier: "", blurb: "",
                 prerequisites: [], skills_built: [], skills_assumed: [],
                 weeks: null, concepts: null, mcqs: null, widgets: null, written: false };
      ORDER.push(k);
    }
    return IDX[k];
  }
  function mergeInto(rec, src, written) {
    var i, ids;
    if (!rec || !src) return;
    if (trim(src.code)) rec.code = trim(src.code);
    if (trim(src.slug)) rec.slug = trim(src.slug);
    if (trim(src.title)) rec.title = trim(src.title);
    if (trim(src.instructor)) rec.instructor = trim(src.instructor);
    if (trim(src.quarter)) rec.quarter = trim(src.quarter);
    if (num(src.units, 0)) rec.units = num(src.units, 0);
    if (trim(src.block)) rec.block = trim(src.block);
    if (trim(src.tier)) rec.tier = trim(src.tier);
    if (trim(src.blurb)) rec.blurb = trim(src.blurb);
    else if (trim(src.description) && !rec.blurb) rec.blurb = trim(src.description);
    ids = arr(src.concentrations);
    for (i = 0; i < ids.length; i++) if (indexOf(rec.concentrations, ids[i]) < 0) rec.concentrations.push(ids[i]);
    if (arr(src.prerequisites).length) rec.prerequisites = arr(src.prerequisites);
    else if (arr(src.prereqs).length) rec.prerequisites = arr(src.prereqs);
    if (arr(src.skills_built).length) rec.skills_built = arr(src.skills_built);
    if (arr(src.skills_assumed).length) rec.skills_assumed = arr(src.skills_assumed);
    if (src.weeks !== undefined && src.weeks !== null) {
      rec.weeks = Object.prototype.toString.call(src.weeks) === "[object Array]"
        ? src.weeks.length : num(src.weeks, null);
    }
    if (src.concepts !== undefined && src.concepts !== null && typeof src.concepts === "number") rec.concepts = num(src.concepts, null);
    if (src.mcqs !== undefined && src.mcqs !== null) rec.mcqs = num(src.mcqs, null);
    if (src.widgets !== undefined && src.widgets !== null && typeof src.widgets === "number") rec.widgets = num(src.widgets, null);
    if (written) rec.written = true;
  }
  (function buildIndex() {
    var i, j, b, c, list, rec;
    for (i = 0; i < BLOCKS.length; i++) {
      b = BLOCKS[i]; list = arr(b.courses);
      for (j = 0; j < list.length; j++) { rec = touch(list[j]); if (rec && !rec.block) rec.block = txt(b.id); }
    }
    for (i = 0; i < CONCS.length; i++) {
      c = CONCS[i]; list = arr(c.courses);
      for (j = 0; j < list.length; j++) {
        rec = touch(list[j]);
        if (rec && indexOf(rec.concentrations, c.id) < 0) rec.concentrations.push(c.id);
      }
    }
    list = arr(P.courses).length ? arr(P.courses) : arr(P.course_index);
    for (i = 0; i < list.length; i++) { rec = touch(list[i] && (list[i].code || list[i].slug)); mergeInto(rec, list[i], false); }
    list = arr(SK.courses);
    for (i = 0; i < list.length; i++) { rec = touch(list[i] && (list[i].code || list[i].slug)); mergeInto(rec, list[i], true); }
    /* anything already in window.COURSES (a wrapper may have loaded one) */
    var deep = obj(window.COURSES), k2;
    for (k2 in deep) if (has(deep, k2)) { rec = touch(k2); mergeInto(rec, deep[k2], true); }
    /* fill in the display code from the slug when only a slug was known */
    for (i = 0; i < ORDER.length; i++) {
      rec = IDX[ORDER[i]];
      if (!trim(rec.code)) rec.code = codeOf(rec.slug);
      if (!trim(rec.title)) rec.title = "";
      if (!trim(rec.block)) rec.block = "";
    }
  }());
  function courseList() {
    var out = [], i;
    for (i = 0; i < ORDER.length; i++) out.push(IDX[ORDER[i]]);
    out.sort(function (a, b) {
      var ba = blockPos(a.block), bb = blockPos(b.block);
      if (ba !== bb) return ba - bb;
      return a.code < b.code ? -1 : (a.code > b.code ? 1 : 0);
    });
    return out;
  }
  function blockPos(id) {
    var i;
    for (i = 0; i < BLOCKS.length; i++) if (BLOCKS[i].id === id) return i;
    return 99;
  }
  function courseByAny(s) { return IDX[ckey(s)] || null; }
  function courseHref(rec) { return "course.html?c=" + encodeURIComponent(rec.code || rec.slug); }

  /* ── prerequisite graph, derived from the prerequisite prose ───────── */
  var NEEDS = {}, FEEDS = {};
  (function () {
    var all = courseList(), i, j, codes, k, t;
    for (i = 0; i < all.length; i++) { NEEDS[all[i].key] = []; FEEDS[all[i].key] = []; }
    for (i = 0; i < all.length; i++) {
      codes = [];
      for (j = 0; j < all[i].prerequisites.length; j++) {
        var found = codesIn(all[i].prerequisites[j]);
        for (k = 0; k < found.length; k++) {
          t = ckey(found[k]);
          if (t && t !== all[i].key && IDX[t] && indexOf(codes, t) < 0) codes.push(t);
        }
      }
      NEEDS[all[i].key] = codes;
      for (j = 0; j < codes.length; j++) {
        if (FEEDS[codes[j]] && indexOf(FEEDS[codes[j]], all[i].key) < 0) FEEDS[codes[j]].push(all[i].key);
      }
    }
  }());

  /* ══════════════ shared chrome ══════════════ */
  function siteName() { return sp("program_short", sp("program", "Curriculum")) + " " + sp("site_title", "Curriculum Arena"); }
  function buildNav(crumbs, right) {
    var nav = $("nav"), k, c, a;
    if (!nav) return;
    clear(nav);
    a = add(nav, el("a", null, siteName()));
    a.href = "index.html";
    c = add(nav, el("span", "crumbs"));
    crumbs = arr(crumbs);
    for (k = 0; k < crumbs.length; k++) {
      if (k) add(c, document.createTextNode(" · "));
      if (crumbs[k].href) { a = add(c, el("a", null, crumbs[k].label)); a.href = crumbs[k].href; }
      else add(c, el("b", null, crumbs[k].label));
    }
    add(nav, el("span", "spacer"));
    a = add(nav, el("a", "crumbs", "Skills")); a.href = "skills.html";
    a = add(nav, el("a", "crumbs", "By quarter")); a.href = "quarter.html";
    if (right && right.href) { a = add(nav, el("a", "crumbs", right.label)); a.href = right.href; }
  }
  function buildFooter() {
    var f = $("foot"), a;
    if (!f) return;
    clear(f);
    f.appendChild(document.createTextNode(
      sp("degree", sp("program", "the programme")) + " · " + sp("institution", "the university") +
      " · curriculum dashboard. Progress is stored in this browser only. "));
    if (sp("source_url")) { a = add(f, el("a", null, "Source")); a.href = sp("source_url"); a.rel = "noopener"; }
  }
  function stubStrip() {
    if (!P.stub) return;
    var b = document.body, s = el("div", "stubstrip",
      "Stub data: program.js has not been harvested yet, so the map below is placeholder content.");
    if (b && b.firstChild) b.insertBefore(s, b.firstChild); else if (b) b.appendChild(s);
  }
  function fail(msg, detail) {
    var host = $("app") || document.body, s;
    clear(host);
    s = add(host, el("section"));
    add(s, el("div", "kicker", "Nothing to show"));
    add(s, el("h1", null, msg));
    if (detail) add(s, el("p", "lead", detail));
    var r = add(s, el("div", "row"));
    var a = add(r, el("a", "btn", "Back to the map")); a.href = "index.html";
  }
  function setTitle(t) { try { document.title = t; } catch (e) { /* ignore */ } }
  function setDesc(t) {
    var m = document.querySelector('meta[name="description"]');
    if (m) m.setAttribute("content", t);
  }
  function statStrip(host, items) {
    var i, s, d;
    if (!host) return;
    clear(host);
    for (i = 0; i < items.length; i++) {
      s = add(host, el("div", "stat"));
      add(s, el("div", "sl", items[i][0]));
      d = add(s, el("div", "sv" + (items[i][2] ? " " + items[i][2] : ""), items[i][1]));
      if (items[i][3]) d.title = items[i][3];
    }
  }
  function pill(text, cls) { return el("span", "pill" + (cls ? " " + cls : ""), text); }
  function setBar(id, p) { var b = $(id); if (b) b.style.width = Math.max(0, Math.min(100, p)) + "%"; }

  /* ══════════════ KaTeX (optional, formulas only) ══════════════ */
  var texNodes = [];
  function renderTex(host, tex, display) {
    var t = trim(tex);
    if (!t) return null;
    var node = el("span");
    node.setAttribute("data-tex", t);
    node.setAttribute("data-display", display ? "1" : "0");
    add(host, node);
    texNodes.push(node);
    typeset(node);
    return node;
  }
  function typeset(node) {
    var t = node.getAttribute("data-tex"), disp = node.getAttribute("data-display") === "1";
    if (window.katex && window.katex.render) {
      try {
        clear(node);
        window.katex.render(t, node, { displayMode: disp, throwOnError: false, output: "html" });
        node.setAttribute("data-done", "1");
        return;
      } catch (e) { /* fall through to the monospace fallback */ }
    }
    if (node.getAttribute("data-done") === "1") return;
    clear(node);
    add(node, el("code", "texfall", t));
  }
  function typesetAll() { var i; for (i = 0; i < texNodes.length; i++) typeset(texNodes[i]); }
  window.FMCA = { typesetAll: typesetAll };

  /* ══════════════ explain: a strict HTML allow-list ══════════════
     SCHEMA.md says `explain` may contain "plain HTML". Rather than trust it,
     the string is parsed with DOMParser and re-built node by node, keeping
     only these tags and dropping every attribute except href on <a> (and
     only http/https/mailto/# hrefs). Anything else becomes its text. */
  var OK_TAGS = { P: 1, BR: 1, EM: 1, I: 1, STRONG: 1, B: 1, CODE: 1, UL: 1, OL: 1, LI: 1,
                  SUP: 1, SUB: 1, SPAN: 1, A: 1, DIV: 1, SMALL: 1, ABBR: 1, KBD: 1, MARK: 1 };
  function safeHref(h) {
    var s = trim(h);
    return (/^(https?:\/\/|mailto:|#|[A-Za-z0-9_.-]+\.html)/).test(s) ? s : "";
  }
  function copyNodes(src, dst) {
    var i, n, out, href;
    for (i = 0; i < src.childNodes.length; i++) {
      n = src.childNodes[i];
      if (n.nodeType === 3) { dst.appendChild(document.createTextNode(n.nodeValue)); continue; }
      if (n.nodeType !== 1) continue;
      if (!OK_TAGS[n.nodeName]) { copyNodes(n, dst); continue; }
      out = document.createElement(n.nodeName.toLowerCase());
      if (n.nodeName === "A") {
        href = safeHref(n.getAttribute("href"));
        if (href) {
          out.setAttribute("href", href);
          if (href.indexOf("http") === 0) { out.setAttribute("target", "_blank"); out.setAttribute("rel", "noopener noreferrer"); }
        }
      }
      copyNodes(n, out);
      dst.appendChild(out);
    }
  }
  function renderExplain(host, source) {
    var s = trim(source), doc, wrap, paras, i, t;
    if (!s) return;
    if (!/[<][a-zA-Z/]/.test(s)) {           /* plain text: split on blank lines */
      paras = s.split(/\n{2,}/);
      for (i = 0; i < paras.length; i++) { t = trim(paras[i]); if (t) add(host, el("p", null, t)); }
      return;
    }
    try {
      doc = new window.DOMParser().parseFromString("<body>" + s + "</body>", "text/html");
      wrap = doc && doc.body;
    } catch (e) { wrap = null; }
    if (!wrap) { add(host, el("p", null, s.replace(/<[^>]*>/g, ""))); return; }
    copyNodes(wrap, host);
  }

  /* ══════════════ code blocks (source + captured output) ══════════════ */
  function copyToClipboard(text, btn) {
    function done(ok) {
      btn.textContent = ok ? "copied" : "copy failed";
      btn.className = "btn tiny copy noprint" + (ok ? " ok" : "");
      window.setTimeout(function () { btn.textContent = "copy"; btn.className = "btn tiny copy noprint"; }, 1600);
    }
    function legacy() {
      try {
        var ta = document.createElement("textarea");
        ta.value = text; ta.setAttribute("readonly", "readonly");
        ta.style.position = "fixed"; ta.style.left = "-2000px"; ta.style.top = "0";
        document.body.appendChild(ta); ta.select();
        var ok = document.execCommand("copy");
        document.body.removeChild(ta);
        done(!!ok);
      } catch (e) { done(false); }
    }
    if (window.navigator && window.navigator.clipboard && window.navigator.clipboard.writeText) {
      try { window.navigator.clipboard.writeText(text).then(function () { done(true); }, legacy); return; }
      catch (e) { /* fall through */ }
    }
    legacy();
  }
  var LANG_LABEL = { python: "python", py: "python", cpp: "c++", "c++": "c++", r: "R" };
  function codeBlock(code, what) {
    var src = txt(code && code.src).replace(/\s+$/, "");
    var out = txt(code && code.output).replace(/\s+$/, "");
    var lang = trim(code && code.lang).toLowerCase();
    var wrap = el("div", "cb"), head, btn, pre, ob;
    head = add(wrap, el("div", "cbh"));
    add(head, el("span", "chip dimchip", LANG_LABEL[lang] || (lang || "code")));
    btn = add(head, el("button", "btn tiny copy noprint", "copy"));
    btn.type = "button";
    btn.setAttribute("aria-label", "Copy the code" + (what ? " for " + what : ""));
    pre = add(wrap, el("pre", "code"));
    add(pre, el("code", null, src));
    btn.addEventListener("click", function () { copyToClipboard(src, btn); });
    if (out) {
      ob = add(wrap, el("div", "cbo"));
      add(ob, el("div", "ol", "output — captured by running this code"));
      add(add(ob, el("pre")), document.createTextNode(out));
    }
    return wrap;
  }

  /* ══════════════ skill tag chips ══════════════ */
  function tagChip(tag, kind) {
    var a = el("a", "chip " + (kind || "built"), tagLabel(tag));
    a.href = "skills.html#" + encodeURIComponent(tag);
    a.title = (kind === "assumed" ? "Assumed: " : "Built: ") + tag + " — see every course that touches it";
    return a;
  }
  function tagList(host, tags, kind, emptyText) {
    var i, box = add(host, el("div", "chips"));
    tags = arr(tags);
    if (!tags.length) { add(host, el("p", "sub", emptyText || "None listed.")); return; }
    for (i = 0; i < tags.length; i++) add(box, tagChip(tags[i], kind));
  }

  /* ══════════════ a course card (used on three pages) ══════════════ */
  function courseCard(rec, opts) {
    opts = obj(opts);
    var written = !!rec.written;
    var card = el(written ? "a" : "div", "ccard" + (written ? "" : " unwritten"));
    var acc = accentOfCourse(rec);
    if (acc) card.style.borderLeftColor = acc;
    if (written) { card.href = courseHref(rec); }
    var cc = add(card, el("div", "cc"));
    add(cc, el("span", "code", rec.code));
    if (rec.quarter) add(cc, pill(rec.quarter));
    add(card, el("div", "ti", rec.title || "Title not harvested yet"));
    var meta = [];
    if (rec.instructor) meta.push(rec.instructor);
    if (rec.units) meta.push(rec.units + " units");
    if (rec.block) meta.push(blockOf(rec.block).name);
    if (meta.length) add(card, el("div", "me", meta.join(" · ")));
    var tags = add(card, el("div", "tags")), i, ids = arr(rec.concentrations);
    for (i = 0; i < ids.length && i < 3; i++) {
      var pl = add(tags, pill(concOf(ids[i]).name, "acc"));
      var a2 = trim(concOf(ids[i]).accent);
      if (a2) { pl.style.borderColor = a2; pl.style.color = a2; }
    }
    if (ids.length > 3) add(tags, pill("+" + (ids.length - 3)));

    if (written) {
      var pr = progressOf(rec.slug);
      var bits = [];
      bits.push(pr.weeks + (rec.weeks ? "/" + rec.weeks : "") + " weeks read");
      bits.push(pr.right + (rec.mcqs ? "/" + rec.mcqs : "") + " checks right");
      add(card, el("div", "prog", bits.join("  ·  ")));
      if (rec.weeks) {
        var bar = add(card, el("div", "bar thin"));
        var fill = add(bar, el("i"));
        fill.style.width = Math.max(0, Math.min(100, pct(pr.weeks, rec.weeks))) + "%";
      }
      add(card, el("div", "go", "Open the course"));
    } else {
      add(card, el("div", "prog", "deep page not written yet"));
    }

    if (opts.prereqs !== false) card.appendChild(prereqPop(rec));
    return card;
  }
  function prereqPop(rec) {
    var pop = el("div", "prereqpop"), needs = arr(NEEDS[rec.key]), feeds = arr(FEEDS[rec.key]), i, line;
    add(pop, el("b", null, "Needs first"));
    if (needs.length) {
      line = add(pop, el("div"));
      for (i = 0; i < needs.length; i++) {
        if (i) add(line, document.createTextNode(", "));
        add(line, document.createTextNode(IDX[needs[i]].code));
      }
    } else if (arr(rec.prerequisites).length) {
      add(pop, el("div", null, rec.prerequisites.join("; ")));
    } else {
      add(pop, el("div", null, "Nothing in the programme — background only."));
    }
    add(pop, el("b", null, "Feeds"));
    if (feeds.length) {
      line = add(pop, el("div"));
      for (i = 0; i < feeds.length; i++) {
        if (i) add(line, document.createTextNode(", "));
        add(line, document.createTextNode(IDX[feeds[i]].code));
      }
    } else {
      add(pop, el("div", null, "No later course names it as a prerequisite."));
    }
    if (arr(rec.skills_built).length) {
      add(pop, el("b", null, "Builds"));
      add(pop, el("div", null, rec.skills_built.slice(0, 6).join(", ") +
        (rec.skills_built.length > 6 ? ", …" : "")));
    }
    return pop;
  }

  /* ══════════════ select helpers ══════════════ */
  function fillSelect(sel, options, anyLabel) {
    var i, o;
    if (!sel) return;
    clear(sel);
    o = add(sel, el("option", null, anyLabel || "All"));
    o.value = "";
    for (i = 0; i < options.length; i++) {
      o = add(sel, el("option", null, options[i][1]));
      o.value = options[i][0];
    }
  }
  function onAny(nodes, ev, fn) {
    var i;
    for (i = 0; i < nodes.length; i++) if (nodes[i]) nodes[i].addEventListener(ev, fn);
  }

  /* ═══════════════════ PAGE: index — the program map ═══════════════════ */
  function renderIndex() {
    setTitle(siteName());
    buildNav([{ label: "Programme map" }]);
    buildFooter();
    stubStrip();

    var all = courseList();
    var written = 0, i;
    for (i = 0; i < all.length; i++) if (all[i].written) written++;

    /* header stats */
    var totalWeeks = 0, totalMcq = 0;
    for (i = 0; i < all.length; i++) { totalWeeks += num(all[i].weeks, 0); totalMcq += num(all[i].mcqs, 0); }
    statStrip($("hStats"), [
      ["Courses", String(all.length)],
      ["Deep pages", String(written), written ? "acc" : ""],
      ["Concentrations", String(CONCS.length)],
      ["Units to graduate", num(P.units_total, 0) ? String(P.units_total) : "—"],
      ["Weeks written", totalWeeks ? String(totalWeeks) : "—"],
      ["Self-check questions", totalMcq ? String(totalMcq) : "—"]
    ]);

    /* header links */
    var links = $("hLinks"), a;
    if (links) {
      clear(links);
      a = add(links, el("a", "lk")); a.href = "skills.html";
      add(a, el("span", "lt", "Vocabulary")); add(a, el("span", "lv", "Every skill, built and assumed"));
      a = add(links, el("a", "lk")); a.href = "quarter.html";
      add(a, el("span", "lt", "Scheduling")); add(a, el("span", "lv", "The load, quarter by quarter"));
      if (sp("catalog_url")) {
        a = add(links, el("a", "lk")); a.href = sp("catalog_url");
        a.target = "_blank"; a.rel = "noopener noreferrer";
        add(a, el("span", "lt", "Official")); add(a, el("span", "lv", "The programme's own curriculum page"));
      }
    }
    var sn = $("srcNote");
    if (sn) {
      sn.textContent = "Every course page is built from the public " + sp("institution", "university") +
        " course page. The syllabus PDFs are behind a " +
        sp("institution_short", sp("institution", "university")) +
        " login, so each page's week-by-week outline, explanations, code, questions and glossary are " +
        "the dashboard's own reconstruction of a standard treatment of those topics, not the " +
        "instructor's material." + (sp("contact") ? " Corrections welcome: " + sp("contact") + "." : "");
    }

    /* filters */
    var bOpts = [], cOpts = [], qOpts = [], sOpts = [];
    for (i = 0; i < BLOCKS.length; i++) bOpts.push([BLOCKS[i].id, BLOCKS[i].name]);
    for (i = 0; i < CONCS.length; i++) cOpts.push([CONCS[i].id, CONCS[i].name]);
    for (i = 0; i < QUARTERS.length; i++) qOpts.push([QUARTERS[i], QUARTERS[i]]);
    var tagsSorted = TAGS.slice().sort(function (x, y) { return x.tag < y.tag ? -1 : 1; });
    for (i = 0; i < tagsSorted.length; i++) sOpts.push([tagsSorted[i].tag, tagLabel(tagsSorted[i].tag)]);
    fillSelect($("fBlock"), bOpts, "Any block");
    fillSelect($("fConc"), cOpts, "Any concentration");
    fillSelect($("fQtr"), qOpts, "Any quarter");
    fillSelect($("fSkill"), sOpts, sOpts.length ? "Any skill" : "No skills.js yet");
    if (!sOpts.length && $("fSkill")) $("fSkill").disabled = true;

    function matches(rec) {
      var q = trim($("fQ") && $("fQ").value).toLowerCase();
      var b = $("fBlock") && $("fBlock").value;
      var c = $("fConc") && $("fConc").value;
      var qr = $("fQtr") && $("fQtr").value;
      var sk = $("fSkill") && $("fSkill").value;
      var w = $("fWritten") && $("fWritten").value;
      if (b && rec.block !== b) return false;
      if (c && indexOf(rec.concentrations, c) < 0) return false;
      if (qr && rec.quarter !== qr) return false;
      if (sk && indexOf(rec.skills_built, sk) < 0 && indexOf(rec.skills_assumed, sk) < 0) return false;
      if (w === "yes" && !rec.written) return false;
      if (w === "no" && rec.written) return false;
      if (q) {
        var hay = (rec.code + " " + rec.title + " " + rec.instructor + " " + rec.blurb + " " +
          rec.skills_built.join(" ") + " " + rec.skills_assumed.join(" ")).toLowerCase();
        if (hay.indexOf(q) < 0) return false;
      }
      return true;
    }

    var mapHost = $("map");
    function draw() {
      var shown = 0, k, j, grp, hd, cards, list, b;
      clear(mapHost);
      var groups = BLOCKS.slice();
      /* a synthetic group for anything program.js never placed in a block */
      var loose = [];
      for (k = 0; k < all.length; k++) if (!blockById[all[k].block]) loose.push(all[k]);
      if (loose.length) groups = groups.concat([{ id: "__loose", name: "Not placed in a block", units: 0,
        blurb: "These codes appear in a concentration or a course file but in no block list.", courses: [] }]);

      for (j = 0; j < groups.length; j++) {
        b = groups[j];
        list = [];
        for (k = 0; k < all.length; k++) {
          var inGroup = b.id === "__loose" ? !blockById[all[k].block] : all[k].block === b.id;
          if (inGroup && matches(all[k])) list.push(all[k]);
        }
        if (!list.length) continue;
        grp = add(mapHost, el("div", "blockgrp"));
        hd = add(grp, el("div", "blockhd"));
        add(hd, el("span", "bn", b.name));
        if (num(b.units, 0)) add(hd, el("span", "bu", b.units + " units"));
        add(hd, el("span", "bu", list.length + " " + plural(list.length, "course")));
        if (trim(b.blurb)) add(hd, el("span", "bb", b.blurb));
        cards = add(grp, el("div", "cards"));
        for (k = 0; k < list.length; k++) { add(cards, courseCard(list[k])); shown++; }
      }
      if (!shown) add(mapHost, el("p", "empty", "No course matches those filters."));
      var fc = $("fCount");
      if (fc) fc.textContent = shown + " of " + all.length + " " + plural(all.length, "course") + " shown.";

      /* overall progress line */
      var pw = 0, pm = 0, tw = 0, tm = 0;
      for (k = 0; k < all.length; k++) {
        var pr = progressOf(all[k].slug);
        pw += pr.weeks; pm += pr.right;
        tw += num(all[k].weeks, 0); tm += num(all[k].mcqs, 0);
      }
      var pl = $("progLine");
      if (pl) {
        pl.textContent = tw
          ? ("You have read " + pw + " of " + tw + " weeks (" + pct(pw, tw) + "%) and answered " +
             pm + " of " + tm + " check questions correctly.")
          : "Open a course to start tracking progress.";
      }
      setBar("barAll", tw ? pct(pw, tw) : 0);
    }

    onAny([$("fQ")], "input", draw);
    onAny([$("fBlock"), $("fConc"), $("fQtr"), $("fSkill"), $("fWritten")], "change", draw);
    if ($("btnClearF")) $("btnClearF").addEventListener("click", function () {
      if ($("fQ")) $("fQ").value = "";
      var ss = [$("fBlock"), $("fConc"), $("fQtr"), $("fSkill"), $("fWritten")], z;
      for (z = 0; z < ss.length; z++) if (ss[z]) ss[z].value = "";
      draw();
    });

    /* concentrations */
    var cg = $("concGrid"), j2;
    if (cg) {
      clear(cg);
      for (j2 = 0; j2 < CONCS.length; j2++) {
        (function (c) {
          var card = add(cg, el("a", "ccard"));
          card.href = "concentration.html?c=" + encodeURIComponent(c.id);
          if (trim(c.accent)) card.style.borderLeftColor = c.accent;
          add(card, el("div", "ti", c.name));
          var m = [];
          if (num(c.units_needed, 0)) m.push(c.units_needed + " units needed");
          if (num(c.units_available, 0)) m.push(c.units_available + " available");
          m.push(arr(c.courses).length + " " + plural(arr(c.courses).length, "course"));
          add(card, el("div", "me", m.join(" · ")));
          if (trim(c.blurb)) add(card, el("div", "prog", c.blurb));
          add(card, el("div", "go", "Open the concentration"));
        }(CONCS[j2]));
      }
      if (!CONCS.length) add(cg, el("p", "empty", "program.js lists no concentrations yet."));
    }

    /* components */
    var cp = $("compGrid"), j3;
    if (cp) {
      clear(cp);
      for (j3 = 0; j3 < COMPONENTS.length; j3++) {
        (function (c) {
          var card = add(cp, el(trim(c.url) ? "a" : "div", "ccard"));
          if (trim(c.url)) { card.href = c.url; card.target = "_blank"; card.rel = "noopener noreferrer"; }
          add(card, el("div", "ti", c.name));
          if (trim(c.blurb)) add(card, el("div", "me", c.blurb));
          if (trim(c.url)) add(card, el("div", "go", "Read more"));
        }(COMPONENTS[j3]));
      }
      if (!COMPONENTS.length) add(cp, el("p", "empty", "program.js lists no extra components."));
    }

    /* privacy / reset */
    show($("lsWarn"), !store.available());
    if ($("btnReset")) $("btnReset").addEventListener("click", function () {
      store.reset();
      draw();
    });
    window.addEventListener("storage", function (ev) {
      if (!ev.key || ev.key.indexOf(PREFIX) === 0) draw();
    });

    draw();
  }

  /* ═══════════════════ PAGE: course — the deep page ═══════════════════ */
  function wantedCourse() {
    var c = trim(window.COURSE_CODE) || trim(qs("c")) || trim(qs("code"));
    var s = trim(window.COURSE_SLUG) || trim(qs("slug"));
    if (!c && s) c = codeOf(s);
    return { code: c, slug: s || slugOf(c) };
  }
  function findLoaded(key) {
    var deep = obj(window.COURSES), k;
    for (k in deep) if (has(deep, k) && ckey(k) === key) return deep[k];
    return null;
  }
  function renderCourse() {
    var want = wantedCourse();
    var key = ckey(want.code);
    buildFooter();
    if (!key) {
      buildNav([{ label: "Course" }]);
      fail("No course was named in the address.",
        "A course page needs ?c=FINM-33000 in its address, or a static wrapper that sets it.");
      return;
    }
    var course = findLoaded(key);
    if (course) { drawCourse(course, want); return; }
    var rec = IDX[key];
    /* Do not even TRY to fetch a course file the index says does not exist.
       skills.js's `courses` array is generated from the files that are
       actually in courses/, so a code that is in program.js but not in that
       array has no page yet. Attempting it anyway would 404, and a 404 is a
       console error — which tools/sweep.py fails a page on, and which would
       otherwise appear on 28 of 29 wrapper pages until the content lands.

       "The index exists" means skills.js was GENERATED — it carries a
       `generated` date and a `courses` array. An EMPTY generated index is
       still authoritative (it means no course has been written yet), which is
       why the test is not `courses.length > 0`. Only a missing or hand-made
       skills.js makes us try the fetch and rely on onerror. */
    var haveIndex = !!(trim(SK.generated) &&
      Object.prototype.toString.call(SK.courses) === "[object Array]");
    if (haveIndex && rec && !rec.written) {
      missingCourse(want, "");
      return;
    }
    var slug = (rec && rec.slug) || want.slug;
    var s = document.createElement("script");
    s.src = "courses/" + slug + ".js";
    s.onload = function () {
      var c2 = findLoaded(key);
      if (c2) drawCourse(c2, want);
      else missingCourse(want, "courses/" + slug + ".js loaded but did not define window.COURSES[\"" +
        (rec ? rec.code : want.code) + "\"].");
    };
    s.onerror = function () { missingCourse(want, ""); };
    document.head.appendChild(s);
  }
  function missingCourse(want, why) {
    var rec = IDX[ckey(want.code)];
    var name = rec ? (rec.code + (rec.title ? " · " + rec.title : "")) : want.code;
    buildNav([{ label: "Courses", href: "index.html" }, { label: want.code }]);
    setTitle(want.code + " · " + siteName());
    fail("The deep page for " + name + " has not been written yet.",
      (why ? why + " " : "") + "The programme map lists it, but courses/" +
      (rec ? rec.slug : want.slug) + ".js is not on the site yet. (If you have just added " +
      "that file, run tools/build_skills.py — the index this page trusts is generated " +
      "from the files in courses/.)");
  }

  function drawCourse(C, want) {
    var rec = IDX[ckey(C.code || want.code)] || touch(C.code || want.code);
    mergeInto(rec, C, true);
    var slug = trim(C.slug) || rec.slug;
    var weeks = arr(C.weeks);
    var acc = accentOfCourse(rec) || accentOfCourse(C);
    if (acc) applyAccent(acc);

    setTitle(rec.code + " · " + (C.title || "") + " · " + siteName());
    if (trim(C.description)) setDesc(trim(C.description).slice(0, 250));
    buildNav([{ label: "Courses", href: "index.html" },
              { label: blockOf(rec.block).name, href: "index.html" },
              { label: rec.code }]);
    stubStrip();

    /* ── header ── */
    var firstConc = arr(C.concentrations)[0] || arr(rec.concentrations)[0] || "";
    var kick = $("hKicker");
    if (kick) kick.textContent = firstConc ? concOf(firstConc).name : blockOf(rec.block).name;
    if ($("hCode")) $("hCode").textContent = rec.code;
    if ($("hTitle")) $("hTitle").textContent = trim(C.title);
    var badges = $("hBadges"), i, j, p;
    if (badges) {
      clear(badges);
      if (trim(C.instructor)) add(badges, pill(C.instructor));
      if (trim(C.quarter)) add(badges, pill(C.quarter, "acc"));
      if (num(C.units, 0)) add(badges, pill(C.units + " units"));
      if (trim(C.block)) add(badges, pill(blockOf(C.block).name));
      var ids = arr(C.concentrations);
      for (i = 0; i < ids.length; i++) {
        p = add(badges, pill(concOf(ids[i]).name, "acc"));
        var a3 = trim(concOf(ids[i]).accent);
        if (a3) { p.style.borderColor = a3; p.style.color = a3; }
      }
      if (trim(C.tier)) add(badges, pill("tier " + C.tier, "warn"))
        .title = "Tier B = derived from the public course page and syllabus.";
    }
    if ($("hDesc")) $("hDesc").textContent = trim(C.description);

    var nConcepts = 0, nWidgets = 0, nMcq = 0;
    for (i = 0; i < weeks.length; i++) {
      nConcepts += arr(weeks[i].concepts).length;
      nMcq += arr(weeks[i].check).length;
      nWidgets += widgetsOf(weeks[i]).length;
    }
    statStrip($("hStats"), [
      ["Weeks", String(weeks.length)],
      ["Concepts", String(nConcepts)],
      ["Widgets", String(nWidgets)],
      ["Check questions", String(nMcq)],
      ["Interview Q&A", String(arr(C.interview).length)],
      ["Glossary", String(arr(C.glossary).length)]
    ]);

    /* header links */
    var links = $("hLinks"), a, src = obj(C.source);
    if (links) {
      clear(links);
      if (trim(src.page_url)) {
        a = add(links, el("a", "lk")); a.href = src.page_url; a.target = "_blank"; a.rel = "noopener noreferrer";
        add(a, el("span", "lt", "Source")); add(a, el("span", "lv", "The official course page"));
      }
      if (trim(src.syllabus_url)) {
        a = add(links, el("a", "lk")); a.href = src.syllabus_url; a.target = "_blank"; a.rel = "noopener noreferrer";
        add(a, el("span", "lt", "Source")); add(a, el("span", "lv", "Syllabus (PDF)"));
      }
      if (firstConc) {
        a = add(links, el("a", "lk")); a.href = "concentration.html?c=" + encodeURIComponent(firstConc);
        add(a, el("span", "lt", "Concentration")); add(a, el("span", "lv", concOf(firstConc).name));
      }
      a = add(links, el("a", "lk")); a.href = "skills.html";
      add(a, el("span", "lt", "Vocabulary")); add(a, el("span", "lv", "Where these skills go next"));
    }

    /* The provenance banner, worded exactly as SCHEMA.md "Page conventions"
       requires. The institution never appears literally here: both names come
       from site_params.js, so swapping schools is still one file. */
    var ban = $("banner");
    if (ban) {
      ban.textContent = "";
      add(ban, el("b", null, "Provenance. "));
      add(ban, document.createTextNode(
        "Built from the public " + sp("institution", "university") + " course page" +
        (trim(src.fetched) ? " (" + trim(src.fetched) + ")" : "") +
        ". The syllabus PDFs are behind a " + sp("institution_short", sp("institution", "university")) +
        " login, so the week-by-week outline, explanations, code, questions and glossary are the " +
        "dashboard's own reconstruction of a standard treatment of these topics, not the " +
        "instructor's material." +
        (sp("contact") ? " Corrections welcome: " + sp("contact") + "." : "")));
    }

    /* ── before week 1 ── */
    var pq = $("preReq");
    if (pq) {
      clear(pq);
      add(pq, el("h3", null, "Prerequisites"));
      var pl2 = arr(C.prerequisites);
      if (pl2.length) {
        var ul = add(pq, el("ul"));
        for (i = 0; i < pl2.length; i++) {
          var li = add(ul, el("li"));
          linkifyCodes(li, pl2[i]);
        }
      } else add(pq, el("p", "sub", "None stated beyond the programme's own admission requirements."));
    }
    var pb = $("preBooks");
    if (pb) {
      clear(pb);
      add(pb, el("h3", null, "Textbooks"));
      var bl = arr(C.textbooks);
      if (bl.length) {
        var ul2 = add(pb, el("ul"));
        for (i = 0; i < bl.length; i++) {
          var li2 = add(ul2, el("li"));
          add(li2, el("b", null, trim(bl[i].title)));
          if (trim(bl[i].author)) add(li2, document.createTextNode(" — " + trim(bl[i].author)));
          if (trim(bl[i].note)) add(li2, el("span", "sub", " · " + trim(bl[i].note)));
        }
      } else add(pb, el("p", "sub", "No set text; the syllabus lists readings per week."));
    }
    var sb = $("skBuilt");
    if (sb) {
      clear(sb);
      add(sb, el("h3", null, "Skills this course builds"));
      tagList(sb, C.skills_built, "built", "No skill tags recorded.");
    }
    var sa = $("skAssumed");
    if (sa) {
      clear(sa);
      add(sa, el("h3", null, "Skills it assumes you have"));
      tagList(sa, C.skills_assumed, "assumed", "Nothing assumed beyond programme admission.");
    }
    var br = $("brush");
    if (br) {
      clear(br);
      br.className = "brush";
      var bu = arr(C.brushup);
      for (i = 0; i < bu.length; i++) {
        var it = add(br, el("div", "bitem"));
        add(it, el("div", "bt", trim(bu[i].topic)));
        if (trim(bu[i].why)) add(it, el("div", "bw", trim(bu[i].why)));
        if (trim(bu[i].resource)) add(it, el("div", "br", trim(bu[i].resource)));
      }
      if (!bu.length) add(br, el("p", "sub", "Nothing listed — arrive with the prerequisites and you are fine."));
    }

    /* ── the weeks ── */
    drawWeeks(C, slug, weeks);

    /* ── interview ── */
    var ivh = $("iv"), iv = arr(C.interview);
    if (ivh) {
      clear(ivh);
      for (i = 0; i < iv.length; i++) ivh.appendChild(qaCard(iv[i], i + 1));
      if (!iv.length) add(ivh, el("p", "empty", "No interview questions recorded for this course yet."));
    }
    if ($("btnRevealAll")) $("btnRevealAll").addEventListener("click", function () { setOpen("#iv details.qa", true); });
    if ($("btnHideAll")) $("btnHideAll").addEventListener("click", function () { setOpen("#iv details.qa", false); });

    /* ── reappears in ── */
    var rh = $("reappears"), re = arr(C.reappears_in);
    if (rh) {
      clear(rh);
      for (i = 0; i < re.length; i++) {
        (function (r) {
          var other = courseByAny(r.code);
          var card = add(rh, el(other && other.written ? "a" : "div", "recard"));
          if (other && other.written) card.href = courseHref(other);
          add(card, el("div", "rc", (other ? other.code : trim(r.code)) +
            (other && other.title ? " · " + other.title : "")));
          add(card, el("div", "rh", trim(r.how)));
        }(re[i]));
      }
      if (!re.length) add(rh, el("p", "empty", "No follow-on courses recorded."));
    }

    /* ── glossary ── */
    var gh = $("glossary"), gl = arr(C.glossary);
    if (gh) {
      clear(gh);
      for (i = 0; i < gl.length; i++) {
        var gi = add(gh, el("div", "gi"));
        add(gi, el("dt", null, trim(gl[i].term)));
        add(gi, el("dd", null, trim(gl[i].def)));
      }
      if (!gl.length) add(gh, el("p", "empty", "No glossary recorded."));
    }

    /* ── prev / next within the block ── */
    var pn = $("pn");
    if (pn) {
      clear(pn);
      var sibs = [], allc = courseList();
      for (i = 0; i < allc.length; i++) if (allc[i].block === rec.block) sibs.push(allc[i]);
      var at = -1;
      for (i = 0; i < sibs.length; i++) if (sibs[i].key === rec.key) at = i;
      function pncard(other, label) {
        if (!other) return;
        var c2 = add(pn, el("a", "pncard"));
        c2.href = courseHref(other);
        add(c2, el("div", "nl", label));
        add(c2, el("div", "nt", other.code + (other.title ? " · " + other.title : "")));
      }
      if (at > 0) pncard(sibs[at - 1], "Previous in " + blockOf(rec.block).name);
      if (at >= 0 && at < sibs.length - 1) pncard(sibs[at + 1], "Next in " + blockOf(rec.block).name);
      var back = add(pn, el("a", "pncard")); back.href = "index.html";
      add(back, el("div", "nl", "Back")); add(back, el("div", "nt", "The whole programme map"));
    }

    if ($("btnPrint")) $("btnPrint").addEventListener("click", function () {
      setOpen("#weeks details.week", true);
      setOpen("#iv details.qa", true);
      try { window.print(); } catch (e) { /* ignore */ }
    });
    window.addEventListener("beforeprint", function () {
      setOpen("#weeks details.week", true);
      setOpen("#iv details.qa", true);
    });
    if (window.SP_APPLY) window.SP_APPLY();
    typesetAll();
  }

  function setOpen(sel, on) {
    var nodes = document.querySelectorAll(sel), i;
    for (i = 0; i < nodes.length; i++) nodes[i].open = !!on;
  }
  /* turn every course code inside a free-text string into a link */
  function linkifyCodes(host, text) {
    var s = txt(text), last = 0, m, rec, a;
    CODE_RE.lastIndex = 0;
    while ((m = CODE_RE.exec(s)) !== null) {
      rec = IDX[ckey(m[0])];
      if (m.index > last) add(host, document.createTextNode(s.slice(last, m.index)));
      if (rec && rec.written) { a = add(host, el("a", null, m[0])); a.href = courseHref(rec); }
      else add(host, el("b", null, m[0]));
      last = m.index + m[0].length;
    }
    if (last < s.length) add(host, document.createTextNode(s.slice(last)));
  }

  function qaCard(item, n) {
    var d = el("details", "qa"), s = add(d, el("summary")), lv = trim(item.level).toLowerCase();
    add(s, el("span", "qn", n + "."));
    add(s, el("span", "qt", trim(item.q)));
    if (lv) add(s, pill(lv, "lv-" + domId(lv)));
    var b = add(d, el("div", "qb"));
    renderExplainOrParas(b, item.answer);
    return d;
  }
  function renderExplainOrParas(host, source) {
    var s = trim(source), paras, i, t;
    if (!s) return;
    if (/[<][a-zA-Z/]/.test(s)) { renderExplain(host, s); return; }
    paras = s.split(/\n{2,}/);
    for (i = 0; i < paras.length; i++) { t = trim(paras[i]); if (t) add(host, el("p", "ap", t)); }
  }

  /* ── the week navigator + the week sections ── */
  function drawWeeks(C, slug, weeks) {
    var host = $("weeks"), nav = $("weeknav"), i;
    if (!host) return;
    clear(host);
    if (!weeks.length) { add(host, el("p", "empty", "No weeks recorded for this course yet.")); return; }

    if (nav) {
      clear(nav);
      show(nav, true);
      add(nav, el("span", "wl", "Weeks"));
      for (i = 0; i < weeks.length; i++) {
        (function (w) {
          var n = num(w.n, 0);
          var a = add(nav, el("a", "wn-link", "W" + n));
          a.href = "#week-" + n;
          a.id = "navw-" + n;
          a.title = trim(w.title);
          if (store.get("w:" + slug + ":" + n) === "1") a.className = "wn-link seen";
        }(weeks[i]));
      }
      add(nav, el("span", "spacer"));
      var pl = add(nav, el("span", "wl"));
      pl.id = "navProg";
    }

    for (i = 0; i < weeks.length; i++) host.appendChild(weekSection(C, slug, weeks[i], i));

    if ($("btnExpand")) $("btnExpand").addEventListener("click", function () { setOpen("#weeks details.week", true); });
    if ($("btnCollapse")) $("btnCollapse").addEventListener("click", function () { setOpen("#weeks details.week", false); });

    /* deep link: #week-3 opens that week */
    var hash = trim(window.location.hash).replace(/^#/, "");
    if (/^week-\d+$/.test(hash)) {
      var target = $(hash);
      if (target) { target.open = true; try { target.scrollIntoView(); } catch (e) { /* ignore */ } }
    }
    updateCourseProgress(slug, weeks);
  }

  function updateCourseProgress(slug, weeks) {
    var pr = progressOf(slug), total = weeks.length, totalQ = 0, i;
    for (i = 0; i < weeks.length; i++) totalQ += arr(weeks[i].check).length;
    var line = $("progLine");
    if (line) {
      line.textContent = pr.weeks + " of " + total + " weeks opened · " +
        pr.right + " of " + totalQ + " check questions answered correctly" +
        (pr.answered ? " (" + pr.answered + " attempted)" : "") + ".";
    }
    setBar("barAll", pct(pr.weeks, total));
    var np = $("navProg");
    if (np) np.textContent = pr.weeks + "/" + total + " read";
    for (i = 0; i < weeks.length; i++) {
      var n = num(weeks[i].n, 0), a = $("navw-" + n);
      if (a) a.className = "wn-link" + (store.get("w:" + slug + ":" + n) === "1" ? " seen" : "");
    }
  }

  function weekSection(C, slug, W, idx) {
    var n = num(W.n, idx + 1);
    var d = el("details", "week");
    d.id = "week-" + n;
    var s = add(d, el("summary"));
    add(s, el("span", "wn", "Week " + n));
    add(s, el("span", "wt", trim(W.title)));
    var meta = add(s, el("span", "wmeta"));
    add(meta, pill(arr(W.concepts).length + " concepts"));
    var nw = widgetsOf(W).length;
    if (nw) add(meta, pill(nw === 1 ? "widget" : nw + " widgets", "acc"));
    if (arr(W.check).length) add(meta, pill(arr(W.check).length + " checks"));
    if (store.get("w:" + slug + ":" + n) === "1") add(meta, pill("read", "ok"));

    var body = add(d, el("div", "wbody"));
    var built = false;
    function build() {
      if (built) return;
      built = true;
      var i, box;
      /* topics */
      if (arr(W.topics).length) {
        box = add(body, el("div", "topics"));
        for (i = 0; i < W.topics.length; i++) add(box, el("span", "chip", trim(W.topics[i])));
      }
      /* concepts */
      var cs = arr(W.concepts);
      for (i = 0; i < cs.length; i++) body.appendChild(conceptCard(cs[i], i + 1));
      /* widget(s) */
      var ws = widgetsOf(W);
      for (i = 0; i < ws.length; i++) body.appendChild(widgetHost(ws[i], C, n));
      /* pitfalls */
      if (arr(W.pitfalls).length) {
        add(body, el("h3", null, "Where this goes wrong")).style.marginTop = "24px";
        box = add(body, el("div", "pitfalls"));
        for (i = 0; i < W.pitfalls.length; i++) {
          var pi = add(box, el("div", "pit"));
          add(pi, el("span", "pm", "pitfall"));
          add(pi, el("span", null, trim(W.pitfalls[i])));
        }
      }
      /* check yourself */
      var ck = arr(W.check);
      if (ck.length) {
        var hd = add(body, el("div", "checkhd"));
        add(hd, el("h3", null, "Check yourself")).style.marginBottom = "0";
        var score = add(hd, el("span", "cs"));
        for (i = 0; i < ck.length; i++) body.appendChild(mcqCard(ck[i], i, slug, n, score, C));
        refreshScore(score, slug, n, ck.length);
      }
    }

    d.addEventListener("toggle", function () {
      if (!d.open) return;
      build();
      if (store.get("w:" + slug + ":" + n) !== "1") {
        store.set("w:" + slug + ":" + n, "1");
        var m = d.querySelector("summary .wmeta");
        if (m) add(m, pill("read", "ok"));
      }
      updateCourseProgress(slug, arr(C.weeks));
    });
    /* printing needs the body even when the week was never opened */
    window.addEventListener("beforeprint", build);
    return d;
  }

  function conceptCard(c, n) {
    var card = el("div", "concept");
    var hd = add(card, el("div", "chd"));
    add(hd, el("div", "cnum", String(n)));
    var tt = add(hd, el("div"));
    add(tt, el("h4", "cti", trim(c.name)));
    var body = add(card, el("div", "ctx"));
    renderExplain(body, c.explain);
    if (trim(c.formula)) {
      var f = add(card, el("div", "formula"));
      renderTex(f, c.formula, true);
    }
    if (c.code && trim(c.code.src)) card.appendChild(codeBlock(c.code, trim(c.name)));
    return card;
  }

  /* SCHEMA.md declares `widget: {…} | null`, one per week. The shell also
     accepts an ARRAY of widget specs — a tolerated superset used only by
     tools/demo_course.js, which has to show all 13 types in five weeks. A
     real course file uses the single-object form. */
  function widgetsOf(W) {
    if (!W || !W.widget) return [];
    if (Object.prototype.toString.call(W.widget) === "[object Array]") {
      var out = [], i;
      for (i = 0; i < W.widget.length; i++) if (W.widget[i]) out.push(W.widget[i]);
      return out;
    }
    return [W.widget];
  }
  function widgetHost(spec, C, weekN) {
    var host = el("div");
    if (!window.WIDGETS || !window.WIDGETS.render) {
      var f = el("figure", "widget");
      add(f, el("figcaption", "wcap", trim(spec.title) || "Interactive figure"));
      add(f, el("p", "wnote", "widgets.js is not loaded, so this figure cannot be drawn."));
      add(host, f);
      return host;
    }
    try { window.WIDGETS.render(host, spec, { course: trim(C.code), week: weekN }); }
    catch (e) {
      var f2 = el("figure", "widget");
      add(f2, el("figcaption", "wcap", trim(spec.title) || "Interactive figure"));
      add(f2, el("p", "wnote", "This figure could not be drawn."));
      add(host, f2);
    }
    return host;
  }

  var LETTERS = "ABCDEFGH";
  function mcqKey(slug, weekN, i) { return "q:" + slug + ":" + weekN + ":" + i; }
  /* the per-week score line. The total lives on the node as data-total so the
     handler never has to be re-bound when a week is rebuilt. */
  function refreshScore(node, slug, weekN) {
    if (!node) return;
    var scan = store.scan("q:" + slug + ":" + weekN + ":"), k, right = 0, done = 0;
    var total = num(node.getAttribute("data-total"), 0);
    for (k in scan) if (has(scan, k)) { done++; if (rightFlag(scan[k])) right++; }
    node.textContent = done
      ? (right + " of " + total + " right, " + done + " attempted")
      : ("none of " + total + " answered yet");
  }
  function mcqCard(q, i, slug, weekN, scoreNode) {
    var box = el("div", "mcq");
    var key = mcqKey(slug, weekN, i);
    var answer = num(q.answer, -1);
    var opts = arr(q.options);
    var qp = add(box, el("p", "q"));
    add(qp, el("span", "qn", (i + 1) + "."));
    add(qp, document.createTextNode(trim(q.q)));
    var list = add(box, el("div", "opts"));
    var fb = el("div", "fb");
    var buttons = [], k, answered = false;

    function settle(chosen, store_it) {
      var right = chosen === answer, j;
      answered = true;
      for (j = 0; j < buttons.length; j++) {
        buttons[j].disabled = true;
        buttons[j].className = "opt " + (j === answer ? "right" : (j === chosen ? "wrong" : "dim"));
      }
      clear(fb);
      add(fb, el("b", null, right ? "Correct. " : "Not quite. "));
      if (!right && answer >= 0 && answer < opts.length) {
        add(fb, el("b", null, "The answer is " + LETTERS.charAt(answer) + ". "));
      }
      add(fb, document.createTextNode(trim(q.why)));
      fb.className = "fb show " + (right ? "good" : "poor");
      box.className = "mcq answered " + (right ? "right" : "wrong");
      if (store_it) store.set(key, (right ? "1" : "0") + ":" + chosen);
      refreshScore(scoreNode, slug, weekN);
    }

    for (k = 0; k < opts.length; k++) {
      (function (j) {
        var b = add(list, el("button", "opt"));
        b.type = "button";
        add(b, el("span", "ol", LETTERS.charAt(j)));
        add(b, document.createTextNode(trim(opts[j])));
        b.addEventListener("click", function () { if (!answered) settle(j, true); });
        buttons.push(b);
      }(k));
    }
    add(box, fb);
    /* replay a stored answer so a reload keeps the exact feedback */
    var prev = store.get(key);
    if (prev !== null && prev !== undefined && prev !== "") {
      var ch = chosenOf(prev);
      settle(ch >= 0 ? ch : (rightFlag(prev) ? answer : -1), false);
    }
    return box;
  }

  /* ═══════════════ PAGE: concentration ═══════════════ */
  function renderConcentration() {
    var id = trim(window.CONC_ID) || trim(qs("c")) || trim(qs("id"));
    buildFooter();
    if (!id || !concById[id]) {
      buildNav([{ label: "Concentration" }]);
      fail(id ? ("No concentration with the id “" + id + "”.") : "No concentration was named in the address.",
        "A concentration page needs ?c=<id> in its address. The ids come from program.js.");
      return;
    }
    var C = concById[id];
    if (trim(C.accent)) applyAccent(C.accent);
    setTitle(C.name + " · " + siteName());
    if (trim(C.blurb)) setDesc(trim(C.blurb).slice(0, 250));
    buildNav([{ label: "Programme map", href: "index.html" }, { label: C.name }]);
    stubStrip();

    if ($("hTitle")) $("hTitle").textContent = C.name;
    if ($("hBlurb")) $("hBlurb").textContent = trim(C.blurb);

    var codes = arr(C.courses), mine = [], i, rec;
    for (i = 0; i < codes.length; i++) { rec = IDX[ckey(codes[i])]; if (rec) mine.push(rec); }
    /* a course may name the concentration without the concentration listing it */
    var all = courseList();
    for (i = 0; i < all.length; i++) {
      if (indexOf(all[i].concentrations, id) >= 0 && indexOf(mine, all[i]) < 0) mine.push(all[i]);
    }
    var writtenN = 0, unitsSum = 0, weeksSum = 0;
    for (i = 0; i < mine.length; i++) {
      if (mine[i].written) writtenN++;
      unitsSum += num(mine[i].units, 0);
      weeksSum += num(mine[i].weeks, 0);
    }
    statStrip($("hStats"), [
      ["Units needed", num(C.units_needed, 0) ? String(C.units_needed) : "—"],
      ["Units available", num(C.units_available, 0) ? String(C.units_available) : String(unitsSum)],
      ["Courses", String(mine.length)],
      ["Deep pages", String(writtenN), writtenN ? "acc" : ""],
      ["Suggested paths", String(arr(C.paths).length)],
      ["Weeks written", weeksSum ? String(weeksSum) : "—"]
    ]);

    var links = $("hLinks"), a;
    if (links) {
      clear(links);
      a = add(links, el("a", "lk")); a.href = "index.html";
      add(a, el("span", "lt", "Context")); add(a, el("span", "lv", "The whole programme map"));
      a = add(links, el("a", "lk")); a.href = "skills.html";
      add(a, el("span", "lt", "Vocabulary")); add(a, el("span", "lv", "Every skill in the degree"));
    }

    /* paths */
    var ph = $("paths"), paths = arr(C.paths), j;
    if (ph) {
      clear(ph);
      for (i = 0; i < paths.length; i++) {
        var row = add(ph, el("div", "pathrow"));
        add(row, el("div", "pn2", trim(paths[i].name)));
        var seq = add(row, el("div", "pathseq")), pc = arr(paths[i].courses);
        for (j = 0; j < pc.length; j++) {
          if (j) add(seq, el("span", "arr", "→"));
          var r2 = IDX[ckey(pc[j])];
          if (r2 && r2.written) {
            var link = add(seq, el("a", "chip built", r2.code + (r2.title ? " · " + r2.title : "")));
            link.href = courseHref(r2);
          } else add(seq, el("span", "chip", r2 ? r2.code : trim(pc[j])));
        }
        if (!pc.length) add(row, el("p", "sub", "No courses listed for this path."));
      }
      if (!paths.length) add(ph, el("p", "empty", "program.js lists no suggested paths for this concentration."));
    }

    /* courses, with a quarter filter */
    var qOpts = [], seenQ = [];
    for (i = 0; i < mine.length; i++) if (mine[i].quarter && indexOf(seenQ, mine[i].quarter) < 0) seenQ.push(mine[i].quarter);
    for (i = 0; i < QUARTERS.length; i++) if (indexOf(seenQ, QUARTERS[i]) >= 0) qOpts.push([QUARTERS[i], QUARTERS[i]]);
    fillSelect($("fQtr"), qOpts, "Any quarter");
    var ch = $("courses");
    function drawCourses() {
      var q = trim($("fQ") && $("fQ").value).toLowerCase();
      var qr = $("fQtr") && $("fQtr").value, k, shown = 0;
      clear(ch);
      for (k = 0; k < mine.length; k++) {
        if (qr && mine[k].quarter !== qr) continue;
        if (q && (mine[k].code + " " + mine[k].title).toLowerCase().indexOf(q) < 0) continue;
        add(ch, courseCard(mine[k]));
        shown++;
      }
      if (!shown) add(ch, el("p", "empty", "No course matches those filters."));
    }
    onAny([$("fQ")], "input", drawCourses);
    onAny([$("fQtr")], "change", drawCourses);
    if ($("btnClearF")) $("btnClearF").addEventListener("click", function () {
      if ($("fQ")) $("fQ").value = "";
      if ($("fQtr")) $("fQtr").value = "";
      drawCourses();
    });
    drawCourses();

    /* skills built by this concentration */
    var sh = $("concSkills"), counts = {}, order = [];
    for (i = 0; i < mine.length; i++) {
      var built = arr(mine[i].skills_built);
      for (j = 0; j < built.length; j++) {
        if (!has(counts, built[j])) { counts[built[j]] = 0; order.push(built[j]); }
        counts[built[j]]++;
      }
    }
    order.sort(function (x, y) { return counts[y] - counts[x] || (x < y ? -1 : 1); });
    if (sh) {
      clear(sh);
      for (i = 0; i < order.length; i++) {
        var chip = add(sh, tagChip(order[i], "built"));
        chip.textContent = tagLabel(order[i]) + " · " + counts[order[i]];
      }
      if (!order.length) add(sh, el("p", "empty",
        "No skill tags yet — run tools/build_skills.py once the course files exist."));
    }

    /* prev / next concentration */
    var pn = $("pn");
    if (pn) {
      clear(pn);
      var at = -1;
      for (i = 0; i < CONCS.length; i++) if (CONCS[i].id === id) at = i;
      function ccard(other, label) {
        if (!other) return;
        var c2 = add(pn, el("a", "pncard"));
        c2.href = "concentration.html?c=" + encodeURIComponent(other.id);
        add(c2, el("div", "nl", label));
        add(c2, el("div", "nt", other.name));
      }
      if (at > 0) ccard(CONCS[at - 1], "Previous concentration");
      if (at >= 0 && at < CONCS.length - 1) ccard(CONCS[at + 1], "Next concentration");
      var back = add(pn, el("a", "pncard")); back.href = "index.html";
      add(back, el("div", "nl", "Back")); add(back, el("div", "nt", "The whole programme map"));
    }
    if (window.SP_APPLY) window.SP_APPLY();
  }

  /* ═══════════════ PAGE: quarter ═══════════════ */
  function renderQuarter() {
    setTitle("By quarter · " + siteName());
    buildNav([{ label: "Programme map", href: "index.html" }, { label: "By quarter" }]);
    buildFooter();
    stubStrip();

    var all = courseList(), i, j;
    var cols = QUARTERS.slice(), unknown = [];
    for (i = 0; i < all.length; i++) if (!all[i].quarter || indexOf(cols, all[i].quarter) < 0) unknown.push(all[i]);

    var totals = {}, k;
    for (i = 0; i < cols.length; i++) totals[cols[i]] = 0;
    for (i = 0; i < all.length; i++) if (has(totals, all[i].quarter)) totals[all[i].quarter] += num(all[i].units, 0);
    var strip = [];
    for (i = 0; i < cols.length; i++) {
      var n = 0;
      for (j = 0; j < all.length; j++) if (all[j].quarter === cols[i]) n++;
      strip.push([cols[i], n + (totals[cols[i]] ? " · " + totals[cols[i]] + "u" : "")]);
    }
    strip.push(["Quarter unknown", String(unknown.length), unknown.length ? "bad" : ""]);
    statStrip($("hStats"), strip);

    var links = $("hLinks"), a;
    if (links) {
      clear(links);
      a = add(links, el("a", "lk")); a.href = "index.html";
      add(a, el("span", "lt", "Context")); add(a, el("span", "lv", "The whole programme map"));
      a = add(links, el("a", "lk")); a.href = "skills.html";
      add(a, el("span", "lt", "Vocabulary")); add(a, el("span", "lv", "Every skill in the degree"));
    }

    var bOpts = [], cOpts = [], qOpts = [];
    for (i = 0; i < BLOCKS.length; i++) bOpts.push([BLOCKS[i].id, BLOCKS[i].name]);
    for (i = 0; i < CONCS.length; i++) cOpts.push([CONCS[i].id, CONCS[i].name]);
    for (i = 0; i < cols.length; i++) qOpts.push([cols[i], cols[i]]);
    fillSelect($("fBlock"), bOpts, "Any block");
    fillSelect($("fConc"), cOpts, "Any concentration");
    fillSelect($("fQtr"), qOpts, "Any quarter");

    function matches(rec) {
      var q = trim($("fQ") && $("fQ").value).toLowerCase();
      var b = $("fBlock") && $("fBlock").value;
      var c = $("fConc") && $("fConc").value;
      if (b && rec.block !== b) return false;
      if (c && indexOf(rec.concentrations, c) < 0) return false;
      if (q) {
        var hay = (rec.code + " " + rec.title + " " + rec.skills_built.join(" ")).toLowerCase();
        if (hay.indexOf(q) < 0) return false;
      }
      return true;
    }

    var host = $("qcols");
    function draw() {
      var only = $("fQtr") && $("fQtr").value, shown = 0, c, list, col, cards, m;
      clear(host);
      var show2 = only ? [only] : cols;
      for (c = 0; c < show2.length; c++) {
        list = [];
        for (m = 0; m < all.length; m++) if (all[m].quarter === show2[c] && matches(all[m])) list.push(all[m]);
        col = add(host, el("div", "qcol"));
        var h = add(col, el("h3"));
        add(h, document.createTextNode(show2[c]));
        var u = 0;
        for (m = 0; m < list.length; m++) u += num(list[m].units, 0);
        add(h, el("span", null, list.length + " " + plural(list.length, "course") + (u ? " · " + u + "u" : "")));
        cards = add(col, el("div", "cards"));
        for (m = 0; m < list.length; m++) { add(cards, courseCard(list[m], { prereqs: false })); shown++; }
        if (!list.length) add(cards, el("p", "sub", "Nothing offered here under these filters."));
      }
      if (!only && unknown.length) {
        list = [];
        for (m = 0; m < unknown.length; m++) if (matches(unknown[m])) list.push(unknown[m]);
        if (list.length) {
          col = add(host, el("div", "qcol"));
          var h2 = add(col, el("h3"));
          add(h2, document.createTextNode("Quarter not recorded"));
          add(h2, el("span", null, list.length + " " + plural(list.length, "course")));
          cards = add(col, el("div", "cards"));
          for (m = 0; m < list.length; m++) { add(cards, courseCard(list[m], { prereqs: false })); shown++; }
        }
      }
      var fc = $("fCount");
      if (fc) fc.textContent = shown + " of " + all.length + " " + plural(all.length, "course") + " shown.";
    }
    onAny([$("fQ")], "input", draw);
    onAny([$("fBlock"), $("fConc"), $("fQtr")], "change", draw);
    if ($("btnClearF")) $("btnClearF").addEventListener("click", function () {
      if ($("fQ")) $("fQ").value = "";
      var ss = [$("fBlock"), $("fConc"), $("fQtr")], z;
      for (z = 0; z < ss.length; z++) if (ss[z]) ss[z].value = "";
      draw();
    });
    draw();

    /* the sequencing table: every prerequisite edge, with its quarters */
    var tb = $("seqBody"), rows = 0;
    if (tb) {
      clear(tb);
      for (i = 0; i < all.length; i++) {
        var needs = arr(NEEDS[all[i].key]);
        for (j = 0; j < needs.length; j++) {
          (function (course, pre) {
            var ia = indexOf(cols, course.quarter), ib = indexOf(cols, pre.quarter);
            var okOrder = (ia < 0 || ib < 0) ? null : (ib < ia);
            var tr = add(tb, el("tr", okOrder === false ? "gap" : ""));
            var td = add(tr, el("td", "nm")); td.setAttribute("data-l", "Course");
            if (course.written) { var a2 = add(td, el("a", null, course.code)); a2.href = courseHref(course); }
            else add(td, document.createTextNode(course.code));
            add(td, el("div", "sub", course.title));
            td = add(tr, el("td", "c", course.quarter || "—")); td.setAttribute("data-l", "Offered");
            td = add(tr, el("td", "nm")); td.setAttribute("data-l", "Needs first");
            if (pre.written) { var a3 = add(td, el("a", null, pre.code)); a3.href = courseHref(pre); }
            else add(td, document.createTextNode(pre.code));
            add(td, el("div", "sub", pre.title));
            td = add(tr, el("td", "c", pre.quarter || "—")); td.setAttribute("data-l", "Offered");
            td = add(tr, el("td", "c")); td.setAttribute("data-l", "Order");
            add(td, pill(okOrder === null ? "unknown" : (okOrder ? "fine" : "check it"),
              okOrder === null ? "" : (okOrder ? "ok" : "warn")));
            rows++;
          }(all[i], IDX[needs[j]]));
        }
      }
      if (!rows) {
        var tr2 = add(tb, el("tr"));
        var td2 = add(tr2, el("td", "nm", "No prerequisite edge names another course in the programme yet."));
        td2.setAttribute("colspan", "5");
      }
    }
    if (window.SP_APPLY) window.SP_APPLY();
  }

  /* ═══════════════ PAGE: skills ═══════════════ */
  function renderSkills() {
    setTitle("Skills · " + siteName());
    buildNav([{ label: "Programme map", href: "index.html" }, { label: "Skills" }]);
    buildFooter();
    stubStrip();

    var rows = TAGS.slice(), i, j;
    /* If skills.js is absent, rebuild a thin vocabulary from whatever the
       course index knows, so the page is still useful. */
    if (!rows.length) {
      var seen = {}, all0 = courseList();
      for (i = 0; i < all0.length; i++) {
        var lists = [["built_in", all0[i].skills_built], ["assumed_in", all0[i].skills_assumed]];
        for (j = 0; j < lists.length; j++) {
          var L = lists[j][1], m;
          for (m = 0; m < L.length; m++) {
            if (!seen[L[m]]) { seen[L[m]] = { tag: L[m], category: "", built_in: [], assumed_in: [] }; rows.push(seen[L[m]]); }
            seen[L[m]][lists[j][0]].push(all0[i].code);
          }
        }
      }
    }
    var gaps = 0, hubs = 0;
    for (i = 0; i < rows.length; i++) {
      if (!arr(rows[i].built_in).length) gaps++;
      if (arr(rows[i].built_in).length >= 3) hubs++;
    }
    statStrip($("hStats"), [
      ["Skill tags", String(rows.length)],
      ["Categories", String(CATS.length || "—")],
      ["Built somewhere", String(rows.length - gaps), "acc"],
      ["Assumed, never built", String(gaps), gaps ? "bad" : "ok"],
      ["Built by 3+ courses", String(hubs)],
      ["Generated", trim(SK.generated) || "—"]
    ]);

    var links = $("hLinks"), a;
    if (links) {
      clear(links);
      a = add(links, el("a", "lk")); a.href = "index.html";
      add(a, el("span", "lt", "Context")); add(a, el("span", "lv", "The whole programme map"));
      a = add(links, el("a", "lk")); a.href = "quarter.html";
      add(a, el("span", "lt", "Scheduling")); add(a, el("span", "lv", "The load, quarter by quarter"));
    }

    var catOpts = [], courseOpts = [], allc = courseList();
    for (i = 0; i < CATS.length; i++) catOpts.push([CATS[i].id, CATS[i].name]);
    if (!catOpts.length) {
      var cseen = [];
      for (i = 0; i < rows.length; i++) if (rows[i].category && indexOf(cseen, rows[i].category) < 0) cseen.push(rows[i].category);
      cseen.sort();
      for (i = 0; i < cseen.length; i++) catOpts.push([cseen[i], cseen[i]]);
    }
    for (i = 0; i < allc.length; i++) courseOpts.push([allc[i].code, allc[i].code + (allc[i].title ? " · " + allc[i].title : "")]);
    fillSelect($("fCat"), catOpts, "Any category");
    fillSelect($("fCourse"), courseOpts, "Any course");

    var tbody = $("tbody");
    function codeCell(td, codes, label) {
      var k, rec;
      td.setAttribute("data-l", label);
      codes = arr(codes);
      if (!codes.length) { add(td, el("span", "sub", "—")); return; }
      for (k = 0; k < codes.length; k++) {
        if (k) add(td, document.createTextNode(" "));
        rec = IDX[ckey(codes[k])];
        if (rec && rec.written) {
          var a2 = add(td, el("a", "chip", rec.code));
          a2.href = courseHref(rec);
          a2.title = rec.title;
        } else add(td, el("span", "chip dimchip", rec ? rec.code : txt(codes[k])));
      }
    }
    function draw() {
      var q = trim($("fQ") && $("fQ").value).toLowerCase();
      var cat = $("fCat") && $("fCat").value;
      var cs = $("fCourse") && $("fCourse").value;
      var bal = $("fBal") && $("fBal").value;
      var shown = 0, k;
      clear(tbody);
      for (k = 0; k < rows.length; k++) {
        var r = rows[k], built = arr(r.built_in), assumed = arr(r.assumed_in);
        if (cat && r.category !== cat) continue;
        if (cs && indexOf(built, cs) < 0 && indexOf(assumed, cs) < 0) continue;
        if (bal === "gap" && built.length) continue;
        if (bal === "built" && !built.length) continue;
        if (bal === "hub" && built.length < 3) continue;
        if (q && (r.tag + " " + txt(r.name) + " " + txt(r.blurb)).toLowerCase().indexOf(q) < 0) continue;
        var tr = add(tbody, el("tr", built.length ? "" : "gap"));
        tr.id = "tag-" + domId(r.tag);
        var td = add(tr, el("td", "nm"));
        td.setAttribute("data-l", "Skill");
        var dot = add(td, el("span", "catdot"));
        dot.style.background = catOf(r.category).color || "#767676";
        add(td, document.createTextNode(tagLabel(r.tag)));
        add(td, el("div", "sub", r.tag));
        if (trim(r.blurb)) add(td, el("div", "sub", r.blurb));
        td = add(tr, el("td", "c", catOf(r.category).name)); td.setAttribute("data-l", "Category");
        codeCell(add(tr, el("td")), built, "Built by");
        codeCell(add(tr, el("td")), assumed, "Assumed by");
        td = add(tr, el("td", "c")); td.setAttribute("data-l", "Balance");
        if (!built.length) add(td, pill("gap", "bad"));
        else if (built.length >= 3) add(td, pill("hub", "acc"));
        else add(td, pill("ok", "ok"));
        shown++;
      }
      show($("empty"), !shown);
      var fc = $("fCount");
      if (fc) fc.textContent = shown + " of " + rows.length + " " + plural(rows.length, "skill") + " shown.";
      highlightHash();
    }
    function highlightHash() {
      var h = trim(window.location.hash).replace(/^#/, "");
      if (!h) return;
      var node = $("tag-" + domId(decodeURIComponent(h)));
      if (!node) return;
      try { node.scrollIntoView(); } catch (e) { /* ignore */ }
      node.style.outline = "2px solid var(--accent-2)";
      window.setTimeout(function () { node.style.outline = ""; }, 2400);
    }
    onAny([$("fQ")], "input", draw);
    onAny([$("fCat"), $("fCourse"), $("fBal")], "change", draw);
    if ($("btnClearF")) $("btnClearF").addEventListener("click", function () {
      if ($("fQ")) $("fQ").value = "";
      var ss = [$("fCat"), $("fCourse"), $("fBal")], z;
      for (z = 0; z < ss.length; z++) if (ss[z]) ss[z].value = "";
      draw();
    });
    window.addEventListener("hashchange", highlightHash);
    draw();
    if (window.SP_APPLY) window.SP_APPLY();
  }

  /* ═══════════════ dispatch ═══════════════ */
  function boot() {
    var page = document.body.getAttribute("data-page");
    try {
      if (page === "index") renderIndex();
      else if (page === "course") renderCourse();
      else if (page === "concentration") renderConcentration();
      else if (page === "quarter") renderQuarter();
      else if (page === "skills") renderSkills();
      else fail("This page does not say which view it is.",
                "Its <body> needs a data-page attribute of index, course, concentration, quarter or skills.");
    } catch (err) {
      fail("This page could not be rendered.", err && err.message ? err.message : String(err));
    }
  }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot);
  else boot();
}());
