/* program.js — degree rules, concentrations, quarters and the course index.
 * Generated from data/courses.csv + the public curriculum pages (2026-09-26).
 * Institution / program names and URLs live in site_params.js, not here.
 */
window.PROGRAM = {
  units_total: 1250,
  units_note: "A full-quarter course is 100 units; a first-half or second-half " +
              "quarter course is 50 units.",
  fetched: "2026-09-26",

  blocks: [
    { id: "core", name: "Core", units: 250, accent: "#800000",
      blurb: "Required of every student: probability and stochastic processes, arbitrage-free option pricing, and portfolio and risk management.",
      courses: [
"FINM 33000",
"FINM 34000",
"FINM 36700"
] },
    { id: "computing", name: "Computing", units: 100, accent: "#155f83",
      blurb: "100 units required out of 300 offered. Any Computing course taken in excess of the requirement counts as an elective and toward the Financial Computing concentration.",
      courses: [
"FINM 32400",
"FINM 32800",
"FINM 33500"
] },
    { id: "electives", name: "Electives", units: 900,
      blurb: "Any FINM course outside the Core and the Computing requirement. At least 600 of the 900 elective units must be strictly FINM courses; a partial list of approved non-FINM electives is published by the program.",
      courses: [
"FINM 31200",
"FINM 32000",
"FINM 32600",
"FINM 32700",
"FINM 32950",
"FINM 33100",
"FINM 33150",
"FINM 33160",
"FINM 33165",
"FINM 33200",
"FINM 34500",
"FINM 34600",
"FINM 34700",
"FINM 34800",
"FINM 35100",
"FINM 35600",
"FINM 35700",
"FINM 35900",
"FINM 37000",
"FINM 37301",
"FINM 37400",
"FINM 37500",
"FINM 37601"
] },
  ],

  concentrations: [
    { id: "financial-computing", name: "Financial Computing",
      units_needed: 300, units_available: 650,
      accent: "#357d96",
      url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/financial-computing/",
      blurb: "Systems and performance engineering for finance: C++ for financial applications, low-latency trading systems and high-performance numerical computing, on top of the developer tooling and research data pipelines taught in the Computing block. Any Computing course taken beyond the 100-unit Computing requirement counts as an elective and toward this concentration, so FINM 32400, 32800 and 33500 are included below.",
      courses: [
"FINM 32400",
"FINM 32600",
"FINM 32700",
"FINM 32800",
"FINM 32950",
"FINM 33500"
],
      paths: [] },
    { id: "machine-learning-ai", name: "Machine Learning and AI",
      units_needed: 300, units_available: 650,
      accent: "#642822",
      url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/machine-learning-and-ai/",
      blurb: "Statistical learning and AI applied to markets: foundations of applied machine learning, machine learning for finance, reinforcement and deep learning, generative and agentic AI, multivariate statistics, modern optimisation, and the econometrics of high-frequency data.",
      courses: [
"FINM 33100",
"FINM 33160",
"FINM 33165",
"FINM 33200",
"FINM 34600",
"FINM 34700",
"FINM 34800"
],
      paths: [] },
    { id: "options-derivatives", name: "Options and Derivatives",
      units_needed: 300, units_available: 300,
      accent: "#8f3931",
      url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/options-and-derivatives/",
      blurb: "Arbitrage-free pricing and hedging beyond the core Options course: stochastic calculus, numerical methods for option pricing, fixed income derivatives, and futures and related derivatives.",
      courses: [
"FINM 32000",
"FINM 34500",
"FINM 37000",
"FINM 37500"
],
      paths: [] },
    { id: "rates-credit", name: "Rates and Credit",
      units_needed: 300, units_available: 300,
      accent: "#b45f20",
      url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/rates-and-credit/",
      blurb: "Interest rates, credit and currencies: fixed income, credit markets, foreign exchange products and pricing, and the blockchain and institutional crypto markets that trade alongside them.",
      courses: [
"FINM 31200",
"FINM 35600",
"FINM 35700",
"FINM 37301",
"FINM 37400"
],
      paths: [] },
    { id: "trading", name: "Trading",
      units_needed: 300, units_available: 350,
      accent: "#58593f",
      url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/trading/",
      blurb: "Strategy design and market structure: quantitative trading strategies across asset classes, macro-finance, information and the structure of markets, and mathematical market microstructure as an optimisation problem.",
      courses: [
"FINM 33150",
"FINM 35100",
"FINM 35900",
"FINM 37601"
],
      paths: [] },
  ],

  quarters: ["Autumn", "Winter", "Spring", "Summer"],
  quarter_note: "FINM 34000 runs as a September Launch in the month before " +
                "Autumn Quarter for the in-person cohort. Summer is Project Lab " +
                "or an internship. Online-program quarters differ from in-person " +
                "quarters and are carried per course as online_quarter.",

  /* ── course index ──────────────────────────────────────────────────
     app.js merges this with blocks[].courses and concentrations[].courses;
     supplying it means the program map has titles, quarters and units
     before any courses/*.js file is loaded. Deep fields (weeks, skills,
     prerequisites, tier) live in courses/finm-XXXXX.js, not here. */
  courses: [
    { code: "FINM 33000", slug: "finm-33000",
      title: "Options",
      instructor: "Roger Lee", quarter: "Autumn", online_quarter: "Autumn 2026",
      units: 100, block: "core", concentrations: [],
      page_url: "https://finmath.uchicago.edu/curriculum/required-courses/finm-33000-mathematical-foundations-of-option-pricing/",
      blurb: "Introduction to the theory of arbitrage-free pricing and hedging of financial derivatives." },
    { code: "FINM 34000", slug: "finm-34000",
      title: "Probability and Stochastic Processes",
      instructor: "Greg Lawler", quarter: "September Launch", online_quarter: "Winter 2026",
      units: 50, block: "core", concentrations: [],
      page_url: "https://finmath.uchicago.edu/curriculum/required-courses/finm-34000/",
      blurb: "This course provides a mathematical introduction to probability and stochastic processes." },
    { code: "FINM 36700", slug: "finm-36700",
      title: "Portfolio and Risk Management",
      instructor: "Mark Hendricks", quarter: "Autumn", online_quarter: "Winter 2026",
      units: 100, block: "core", concentrations: [],
      page_url: "https://finmath.uchicago.edu/curriculum/required-courses/finm-36700/",
      blurb: "The course begins by covering the classic foundations of portfolio theory, including meanvariance mathematics and the standard equity factor models used in attribution, risk management, and pricing." },
    { code: "FINM 32400", slug: "finm-32400",
      title: "Software Developer Tools for Finance",
      instructor: "Shahbaz Chaudhary", quarter: "Autumn", online_quarter: "Summer 2026",
      units: 100, block: "computing", concentrations: [],
      page_url: "https://finmath.uchicago.edu/curriculum/computing/finm-32400/",
      blurb: "This course builds on students\u2019 Python skills to bridge the gap between exploratory coding and production-quality software for financial data science." },
    { code: "FINM 32800", slug: "finm-32800",
      title: "Data Pipelines for Quantitative Research",
      instructor: "Jeremy Bejarano", quarter: "Autumn", online_quarter: "Summer 2026",
      units: 100, block: "computing", concentrations: [],
      page_url: "https://finmath.uchicago.edu/curriculum/computing/finm-32900/",
      blurb: "Data Pipelines for Quantitative Research is a hands-on course centered on building reproducible analytical pipelines: data science workflows that are automated and fully reproducible from end to end\u2014from extraction and\u2026" },
    { code: "FINM 33500", slug: "finm-33500",
      title: "Systematic Trading Technologies",
      instructor: "Sebastien Donadio", quarter: "Autumn", online_quarter: "Winter 2026",
      units: 100, block: "computing", concentrations: [],
      page_url: "https://finmath.uchicago.edu/curriculum/computing/finm-33500/",
      blurb: "The Python engineering behind systematic trading, taught by building the systems that quant desks run on." },
    { code: "FINM 31200", slug: "finm-31200",
      title: "Blockchain and Cryptoassets for Finance",
      instructor: "Brian Boonstra", quarter: "Autumn", online_quarter: "Winter 2027",
      units: 50, block: "electives", concentrations: ["rates-credit"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/rates-and-credit/finm-31200/",
      blurb: "Since before the invention of reeding for the edges of coins, technology has been closely involved with money." },
    { code: "FINM 32000", slug: "finm-32000",
      title: "Numerical Methods",
      instructor: "Roger Lee", quarter: "Spring", online_quarter: "Spring 2026",
      units: 100, block: "electives", concentrations: ["options-derivatives"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/options-and-derivatives/finm-32000/",
      blurb: "Implementing the theory introduced in FINM 33000 (Options) , this course takes a numerical/computational approach to the pricing and hedging of financial derivatives." },
    { code: "FINM 32600", slug: "finm-32600",
      title: "Computing for Finance in C++",
      instructor: "Chanaka Liyanaarachchi", quarter: "Winter", online_quarter: "TBD",
      units: 100, block: "electives", concentrations: ["financial-computing"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/financial-computing/finm-32600/",
      blurb: "Computing for Finance in C++ introduces C++ from the ground up, high-lighting features of modern C++ to write reliable and performance sensitive applications in quantitative finance field." },
    { code: "FINM 32700", slug: "finm-32700",
      title: "Low Latency Trading Systems",
      instructor: "Sebastien Donadio", quarter: "Spring", online_quarter: "Autumn 2026",
      units: 100, block: "electives", concentrations: ["financial-computing"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/financial-computing/finm-32700/",
      blurb: "This course is intended to teach programming concepts and techniques to students desiring to work in the financial sector." },
    { code: "FINM 32950", slug: "finm-32950",
      title: "High-Performance Numerical Computing for Finance",
      instructor: "Chanaka Liyanaarachchi", quarter: "Spring", online_quarter: "TBD",
      units: 50, block: "electives", concentrations: ["financial-computing"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/financial-computing/finm-32950/",
      blurb: "In this course, we delve into high-performance computing within finance applications." },
    { code: "FINM 33100", slug: "finm-33100",
      title: "Foundations of Applied Machine Learning",
      instructor: "Matt Olson", quarter: "Autumn", online_quarter: "Summer 2026",
      units: 50, block: "electives", concentrations: ["machine-learning-ai"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/machine-learning-and-ai/finm-33100/",
      blurb: "This course introduces core machine learning methods, with applications drawn from financial datasets such as cross-sectional equity returns." },
    { code: "FINM 33150", slug: "finm-33150",
      title: "Quantitative Trading Strategies",
      instructor: "Brian Boonstra", quarter: "Winter", online_quarter: "Spring 2026",
      units: 100, block: "electives", concentrations: ["trading"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/trading/finm-33150/",
      blurb: "Quantitative trading strategies, employing investment decisions based on model output, are a major component of business operations in the finance industry worldwide." },
    { code: "FINM 33160", slug: "finm-33160",
      title: "Machine Learning for Finance",
      instructor: "Niels Nygaard", quarter: "Winter", online_quarter: "TBD",
      units: 100, block: "electives", concentrations: ["machine-learning-ai"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/machine-learning-and-ai/finm-33160/",
      blurb: "We are going to construct a large data set of fundamental factors of stocks." },
    { code: "FINM 33165", slug: "finm-33165",
      title: "Reinforcement Learning and Deep Learning",
      instructor: "Niels Nygaard", quarter: "Autumn", online_quarter: "",
      units: 100, block: "electives", concentrations: ["machine-learning-ai"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/machine-learning-and-ai/finm-33165/",
      blurb: "Reinforcement Learning (RL) is actually quite an old discipline, going back to WW2." },
    { code: "FINM 33200", slug: "finm-33200",
      title: "Generative and Agentic AI for Finance",
      instructor: "Jeremy Bejarano; Mark Hendricks", quarter: "Spring", online_quarter: "TBD",
      units: 100, block: "electives", concentrations: ["machine-learning-ai"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/machine-learning-and-ai/finm-33200-1/",
      blurb: "Generative and agentic AI is expanding the toolbox of the quantitative practitioner." },
    { code: "FINM 34500", slug: "finm-34500",
      title: "Stochastic Calculus",
      instructor: "Greg Lawler", quarter: "Winter", online_quarter: "TBD",
      units: 100, block: "electives", concentrations: ["options-derivatives"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/options-and-derivatives/finm-34500/",
      blurb: "The course starts with a quick introduction to martingales in discrete time, and then Brownian motion and the Ito integral are defined carefully." },
    { code: "FINM 34600", slug: "finm-34600",
      title: "The Analysis of High Frequency Data",
      instructor: "Per A. Mykland", quarter: "Winter", online_quarter: "",
      units: 100, block: "electives", concentrations: ["machine-learning-ai"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/machine-learning-and-ai/finm-34600/",
      blurb: "This course is an introduction to the econometric analysis of high-frequency financial data." },
    { code: "FINM 34700", slug: "finm-34700",
      title: "Multivariate Statistical Analysis: Applications and Techniques",
      instructor: "Jingshu Wang", quarter: "Spring", online_quarter: "",
      units: 100, block: "electives", concentrations: ["machine-learning-ai"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/machine-learning-and-ai/finm-34700/",
      blurb: "This course introduces statistical methods for analyzing, modeling, and interpreting multivariate and high-dimensional data." },
    { code: "FINM 34800", slug: "finm-34800",
      title: "Modern Applied Optimization",
      instructor: "Lek-Heng Lim", quarter: "Autumn", online_quarter: "",
      units: 100, block: "electives", concentrations: ["machine-learning-ai"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/machine-learning-and-ai/finm-34800/",
      blurb: "This course assumes no background in optimization." },
    { code: "FINM 35100", slug: "finm-35100",
      title: "Information, Trading, and the Structure of Markets",
      instructor: "Ayan Bhattacharya", quarter: "Spring", online_quarter: "",
      units: 100, block: "electives", concentrations: ["trading"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/trading/finm-35100/",
      blurb: "At the core of trading strategies that drive today\u2019s markets lie foundational concepts in economics and statistics of information." },
    { code: "FINM 35600", slug: "finm-35600",
      title: "Institutional Crypto Markets: Liquidity and Mechanism Design",
      instructor: "Chris Newhouse", quarter: "Autumn", online_quarter: "Summer 2026",
      units: 50, block: "electives", concentrations: ["rates-credit"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/rates-and-credit/finm-35600/",
      blurb: "This practitioner-led course teaches graduate students the market structure of digital asset markets and the business of institutional liquidity provision: how exchanges and derivative instruments are designed, how\u2026" },
    { code: "FINM 35700", slug: "finm-35700",
      title: "Credit Markets",
      instructor: "Alex Popovici", quarter: "Spring", online_quarter: "Autumn 2026",
      units: 100, block: "electives", concentrations: ["rates-credit"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/rates-and-credit/finm-35700/",
      blurb: "The course objective is to introduce students to mathematical modeling, pricing and trading strategies for credit instruments." },
    { code: "FINM 35900", slug: "finm-35900",
      title: "Macro-Finance",
      instructor: "Ian Wright", quarter: "Spring", online_quarter: "Spring 2026",
      units: 50, block: "electives", concentrations: ["trading"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/trading/finm-35900/",
      blurb: "A significant goal of this course is to give you quantitative work while simultaneously evaluating you on your ability to communicate, present and discuss your conclusions, work and ideas." },
    { code: "FINM 37000", slug: "finm-37000",
      title: "Futures and Related Derivatives",
      instructor: "Eric Patterson", quarter: "Autumn", online_quarter: "Summer 2026",
      units: 50, block: "electives", concentrations: ["options-derivatives"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/options-and-derivatives/finm-37000/",
      blurb: "This course will serve as an introduction to futures and related derivatives by providing a survey of models and tools that are useful to a quantitative analyst working with these products." },
    { code: "FINM 37301", slug: "finm-37301",
      title: "Foreign Exchange: Markets, Products & Pricing",
      instructor: "Anthony Capozzoli", quarter: "Spring", online_quarter: "Winter 2026",
      units: 50, block: "electives", concentrations: ["rates-credit"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/rates-and-credit/finm-37301/",
      blurb: "This course will examine international currency markets, financial products, and applications of quantitative models with an emphasis on the quantitative methods and derivative products in common use today." },
    { code: "FINM 37400", slug: "finm-37400",
      title: "Fixed Income",
      instructor: "Mark Hendricks", quarter: "Winter", online_quarter: "Spring 2026",
      units: 50, block: "electives", concentrations: ["rates-credit"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/rates-and-credit/finm-37400/",
      blurb: "This course covers the mathematical modeling, statistical analysis, and market features relevant for pricing and managing fixed income products." },
    { code: "FINM 37500", slug: "finm-37500",
      title: "Fixed Income Derivatives",
      instructor: "Mark Hendricks", quarter: "Winter", online_quarter: "Spring 2026",
      units: 50, block: "electives", concentrations: ["options-derivatives"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/options-and-derivatives/finm-37500/",
      blurb: "The course covers key models and techniques needed to manage and price fixed-income derivatives." },
    { code: "FINM 37601", slug: "finm-37601",
      title: "Mathematical Market Microstructure: An Optimized Approach",
      instructor: "Hongsong Chou", quarter: "Autumn", online_quarter: "Autumn 2026",
      units: 100, block: "electives", concentrations: ["trading"],
      page_url: "https://finmath.uchicago.edu/curriculum/degree-concentrations/trading/finm-37601/",
      blurb: "Market Microstructure is a sub-field in finance and focuses on price formation processes at small time scale (or, high frequency level) and related market participants\u2019 behaviors that can be both the causes and the\u2026" }
  ],

  components: [
    { id: "project-lab", name: "Project Lab", code: "FINM 36000",
      blurb: "Project Lab allows students to work with industry partners on their firms' research projects. It is a 10-week collaboration; each team of four to six students is supported by an advisor, students apply to specific firm projects, and the project concludes with a final presentation to the firm and specific deliverables. Typically offered every quarter and repeatable. Past projects span algorithmic trading on sentiment and news, risk management for illiquid and private securities, options volatility modelling, systematic macro strategies and data analytics.",
      url: "https://finmath.uchicago.edu/curriculum/project-lab/" },
    { id: "career-seminar", name: "Career Seminar", code: "FINM 38500",
      blurb: "Career Seminar supplements coursework with professional development focused on career exploration and the skills top employers expect. Offered quarterly and graded Pass/Fail, it covers the quant finance job market and search strategy, application materials and interviewing, and networking, through employer treks and info sessions, workshops, alumni panels, small-group practice labs and one-on-one advising. Students not seeking an internship or full-time role may be waived with approval from the Career Development Office.",
      url: "https://finmath.uchicago.edu/curriculum/career-seminar/" }
  ]
};
